Repository ParchmentMC/Parchment, pull requests merged in 2021-06, with the labels that each got.

#1 Add some data for BlockPos
  data/classes/a.json
  data/classes/fx.json
  data/packages.json
Labels: 1.16.5, javadocs, parameters

#2 Add docs for standards
  docs/review-merge-process.md
  docs/standards.md
Labels: enhancement, meta

#8 Remove All Prefix Information from Documentation
  docs/standards.md
Labels: meta, parameters

#10 Add enigma batch/shell script for the lazy
  enigma
  enigma.bat
Labels: enhancement

#12 Add contributing document, reword the README
  README.md
  docs/CONTRIBUTING.md
Labels: enhancement

#13 Mapped and Cleaned-up for net/minecraft/nbt
  data/net/minecraft/nbt/CollectionTag.mapping
  data/net/minecraft/nbt/CompoundTag.mapping
  data/net/minecraft/nbt/NbtIo.mapping
  data/net/minecraft/nbt/NbtUtils.mapping
  data/net/minecraft/nbt/SnbtPrinterTagVisitor.mapping
  data/net/minecraft/nbt/TagParser.mapping
  data/net/minecraft/nbt/TextComponentTagVisitor.mapping
Labels: 1.17.x, parameters

#14 Random mappings
  data/net/minecraft/client/Camera.mapping
  data/net/minecraft/client/CameraType.mapping
  data/net/minecraft/client/Game.mapping
  data/net/minecraft/client/GuiMessage.mapping
  data/net/minecraft/client/Minecraft.mapping
  data/net/minecraft/client/Option.mapping
  data/net/minecraft/client/Options.mapping
  data/net/minecraft/client/Timer.mapping
  data/net/minecraft/client/User.mapping
  data/net/minecraft/realms/DisconnectedRealmsScreen.mapping
  data/net/minecraft/realms/RealmsConnect.mapping
  data/net/minecraft/realms/RealmsLabel.mapping
  data/net/minecraft/realms/RealmsObjectSelectionList.mapping
  data/net/minecraft/realms/RealmsScreen.mapping
  data/net/minecraft/realms/RepeatedNarrator.mapping
  data/net/minecraft/tags/GameEventTags.mapping
  data/net/minecraft/tags/StaticTagHelper.mapping
  data/net/minecraft/tags/TagCollection.mapping
  data/net/minecraft/world/SnooperPopulator.mapping
  data/net/minecraft/world/food/FoodData.mapping
  data/net/minecraft/world/food/FoodProperties.mapping
  data/net/minecraft/world/food/Foods.mapping
Labels: 1.17.x, parameters

#20 Fix some typos in review-merge-process.md
  docs/review-merge-process.md
Labels: bug, meta, minor changes, ready to merge

#11 Partially document the entity attribute system.
  data/net/minecraft/world/entity/ai/attributes/Attribute.mapping
  data/net/minecraft/world/entity/ai/attributes/Attributes.mapping
  data/net/minecraft/world/entity/ai/attributes/RangedAttribute.mapping
Labels: 1.17, javadocs, mappings, parameters, ready to merge

#22 Mappings for net/minecraft/world/level/chunk/storage
  data/net/minecraft/world/level/chunk/storage/ChunkStorage.mapping
  data/net/minecraft/world/level/chunk/storage/EntityStorage.mapping
  data/net/minecraft/world/level/chunk/storage/IOWorker.mapping
  data/net/minecraft/world/level/chunk/storage/OldChunkStorage.mapping
  data/net/minecraft/world/level/chunk/storage/RegionBitmap.mapping
  data/net/minecraft/world/level/chunk/storage/RegionFile.mapping
  data/net/minecraft/world/level/chunk/storage/RegionFileStorage.mapping
  data/net/minecraft/world/level/chunk/storage/RegionFileVersion.mapping
  data/net/minecraft/world/level/chunk/storage/SectionStorage.mapping
Labels: 1.17, javadocs, mappings, parameters, ready to merge

#34 Fix CastleTransformer's parameter order
  data/net/minecraft/world/level/newbiome/layer/traits/CastleTransformer.mapping
Labels: 1.17, bug, mappings, minor changes, parameters, ready to merge

#18 More random mappings
  data/net/minecraft/core/AxisCycle.mapping
  data/net/minecraft/core/BlockMath.mapping
  data/net/minecraft/core/BlockSourceImpl.mapping
  data/net/minecraft/core/Cursor3D.mapping
  data/net/minecraft/core/GlobalPos.mapping
  data/net/minecraft/core/NonNullList.mapping
  data/net/minecraft/core/PositionImpl.mapping
  data/net/minecraft/core/Vec3i.mapping
  data/net/minecraft/core/dispenser/BoatDispenseItemBehavior.mapping
  data/net/minecraft/core/dispenser/DispenseItemBehavior.mapping
  data/net/minecraft/core/particles/ParticleGroup.mapping
  data/net/minecraft/core/particles/ParticleType.mapping
  data/net/minecraft/data/BlockFamilies.mapping
  data/net/minecraft/data/BlockFamily.mapping
  data/net/minecraft/data/DataGenerator.mapping
  data/net/minecraft/data/HashCache.mapping
  data/net/minecraft/data/Main.mapping
  data/net/minecraft/sounds/Music.mapping
  data/net/minecraft/sounds/SoundEvent.mapping
  data/net/minecraft/sounds/SoundSource.mapping
  data/net/minecraft/world/entity/npc/VillagerTrades.mapping
  data/net/minecraft/world/entity/npc/VillagerType.mapping
Labels: 1.17, mappings, parameters

#25 mapped a lot of net/minecraft/client/screen/inventory
  data/net/minecraft/client/gui/GuiComponent.mapping
  data/net/minecraft/client/gui/components/AbstractWidget.mapping
  data/net/minecraft/client/gui/components/Widget.mapping
  data/net/minecraft/client/gui/font/TextFieldHelper.mapping
  data/net/minecraft/client/gui/narration/NarrationSupplier.mapping
  data/net/minecraft/client/gui/screens/Screen.mapping
  data/net/minecraft/client/gui/screens/inventory/AbstractCommandBlockEditScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/AbstractContainerScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/AbstractFurnaceScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/AnvilScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/BeaconScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/BlastFurnaceScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/BookEditScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/BrewingStandScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/CartographyTableScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/CommandBlockEditScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/ContainerScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/CraftingScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/CreativeInventoryListener.mapping
  data/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/DispenserScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/EffectRenderingInventoryScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/EnchantmentScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/FurnaceScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/GrindstoneScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/HopperScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/HorseInventoryScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/InventoryScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/ItemCombinerScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/JigsawBlockEditScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/LecternScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/LoomScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/MerchantScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/MinecartCommandBlockEditScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/PageButton.mapping
  data/net/minecraft/client/gui/screens/inventory/ShulkerBoxScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/SignEditScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/SmithingScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/SmokerScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/StonecutterScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/StructureBlockEditScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/tooltip/ClientBundleTooltip.mapping
  data/net/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipComponent.mapping
  data/net/minecraft/world/entity/LivingEntity.mapping
  data/net/minecraft/world/entity/player/Player.mapping
  data/net/minecraft/world/inventory/AbstractContainerMenu.mapping
  data/net/minecraft/world/inventory/ContainerListener.mapping
  data/net/minecraft/world/inventory/Slot.mapping
  data/net/minecraft/world/inventory/tooltip/BundleTooltip.mapping
  data/net/minecraft/world/item/trading/MerchantOffer.mapping
Labels: 1.17, mappings, parameters

#33 Mostly maps net.minecraft.gametest.framework
  data/net/minecraft/gametest/framework/ExhaustedAttemptsException.mapping
  data/net/minecraft/gametest/framework/GameTestAssertException.mapping
  data/net/minecraft/gametest/framework/GameTestAssertPosException.mapping
  data/net/minecraft/gametest/framework/GameTestBatch.mapping
  data/net/minecraft/gametest/framework/GameTestBatchRunner.mapping
  data/net/minecraft/gametest/framework/GameTestEvent.mapping
  data/net/minecraft/gametest/framework/GameTestHelper.mapping
  data/net/minecraft/gametest/framework/GameTestInfo.mapping
  data/net/minecraft/gametest/framework/GameTestListener.mapping
  data/net/minecraft/gametest/framework/GameTestRegistry.mapping
  data/net/minecraft/gametest/framework/GameTestRunner.mapping
  data/net/minecraft/gametest/framework/GameTestSequence.mapping
  data/net/minecraft/gametest/framework/GameTestServer.mapping
  data/net/minecraft/gametest/framework/GameTestTicker.mapping
  data/net/minecraft/gametest/framework/GameTestTimeoutException.mapping
  data/net/minecraft/gametest/framework/GlobalTestReporter.mapping
  data/net/minecraft/gametest/framework/JUnitLikeTestReporter.mapping
  data/net/minecraft/gametest/framework/MultipleTestTracker.mapping
  data/net/minecraft/gametest/framework/ReportGameListener.mapping
  data/net/minecraft/gametest/framework/StructureUtils.mapping
  data/net/minecraft/gametest/framework/TestClassNameArgument.mapping
  data/net/minecraft/gametest/framework/TestCommand.mapping
  data/net/minecraft/gametest/framework/TestFunction.mapping
  data/net/minecraft/gametest/framework/TestFunctionArgument.mapping
  data/net/minecraft/gametest/framework/TestReporter.mapping
  data/net/minecraft/server/MinecraftServer.mapping
Labels: 1.17, mappings, parameters
