Repository ParchmentMC/Parchment, pull requests merged in 2021-07, with the labels that each got.

#23 Some miscellaneous mappings
  data/net/minecraft/client/main/GameConfig.mapping
  data/net/minecraft/client/main/Main.mapping
  data/net/minecraft/client/main/SilentInitException.mapping
  data/net/minecraft/server/Eula.mapping
  data/net/minecraft/server/Main.mapping
  data/net/minecraft/util/ExceptionCollector.mapping
  data/net/minecraft/util/Mth.mapping
  data/net/minecraft/util/profiling/ActiveProfiler.mapping
  data/net/minecraft/util/profiling/ProfileCollector.mapping
  data/net/minecraft/util/profiling/ProfilerFiller.mapping
  data/net/minecraft/util/profiling/ResultField.mapping
  data/net/minecraft/util/random/SimpleWeightedRandomList.mapping
  data/net/minecraft/util/random/Weight.mapping
  data/net/minecraft/util/random/WeightedEntry.mapping
  data/net/minecraft/util/random/WeightedRandom.mapping
  data/net/minecraft/util/random/WeightedRandomList.mapping
  data/net/minecraft/world/BossEvent.mapping
  data/net/minecraft/world/CompoundContainer.mapping
  data/net/minecraft/world/ContainerHelper.mapping
  data/net/minecraft/world/Difficulty.mapping
  data/net/minecraft/world/DifficultyInstance.mapping
  data/net/minecraft/world/InteractionResult.mapping
  data/net/minecraft/world/InteractionResultHolder.mapping
  data/net/minecraft/world/LockCode.mapping
  data/net/minecraft/world/SimpleContainer.mapping
  data/net/minecraft/world/SimpleMenuProvider.mapping
  data/net/minecraft/world/inventory/MenuConstructor.mapping
  data/net/minecraft/world/phys/AABB.mapping
  data/net/minecraft/world/phys/Vec2.mapping
  data/net/minecraft/world/phys/Vec3.mapping
Labels: 1.17, javadocs, mappings, parameters

#9 Partially add parameter names to com/mojang/blaze3d and com/mojang/math
  data/com/mojang/blaze3d/audio/Channel.mapping
  data/com/mojang/blaze3d/audio/Library.mapping
  data/com/mojang/blaze3d/audio/Listener.mapping
  data/com/mojang/blaze3d/audio/OggAudioStream.mapping
  data/com/mojang/blaze3d/audio/OpenAlUtil.mapping
  data/com/mojang/blaze3d/audio/SoundBuffer.mapping
  data/com/mojang/blaze3d/font/GlyphInfo.mapping
  data/com/mojang/blaze3d/font/TrueTypeGlyphProvider.mapping
  data/com/mojang/blaze3d/pipeline/MainTarget.mapping
  data/com/mojang/blaze3d/pipeline/RenderPipeline.mapping
  data/com/mojang/blaze3d/pipeline/RenderTarget.mapping
  data/com/mojang/blaze3d/pipeline/TextureTarget.mapping
  data/com/mojang/blaze3d/platform/ClipboardManager.mapping
  data/com/mojang/blaze3d/platform/DisplayData.mapping
  data/com/mojang/blaze3d/platform/GLX.mapping
  data/com/mojang/blaze3d/platform/GlDebug.mapping
  data/com/mojang/blaze3d/platform/GlUtil.mapping
  data/com/mojang/blaze3d/platform/InputConstants.mapping
  data/com/mojang/blaze3d/platform/MemoryTracker.mapping
  data/com/mojang/blaze3d/platform/Monitor.mapping
  data/com/mojang/blaze3d/platform/MonitorCreator.mapping
  data/com/mojang/blaze3d/platform/NativeImage.mapping
  data/com/mojang/blaze3d/platform/PngInfo.mapping
  data/com/mojang/blaze3d/platform/ScreenManager.mapping
  data/com/mojang/blaze3d/platform/SnooperAccess.mapping
  data/com/mojang/blaze3d/platform/TextureUtil.mapping
  data/com/mojang/blaze3d/platform/VideoMode.mapping
  data/com/mojang/blaze3d/platform/Window.mapping
  data/com/mojang/blaze3d/preprocessor/GlslPreprocessor.mapping
  data/com/mojang/blaze3d/shaders/AbstractUniform.mapping
  data/com/mojang/blaze3d/shaders/BlendMode.mapping
  data/com/mojang/blaze3d/shaders/EffectProgram.mapping
  data/com/mojang/blaze3d/shaders/Program.mapping
  data/com/mojang/blaze3d/shaders/ProgramManager.mapping
  data/com/mojang/blaze3d/shaders/Uniform.mapping
  data/com/mojang/blaze3d/systems/RenderSystem.mapping
  data/com/mojang/blaze3d/vertex/BufferBuilder.mapping
  data/com/mojang/blaze3d/vertex/BufferUploader.mapping
  data/com/mojang/blaze3d/vertex/DefaultVertexFormat.mapping
  data/com/mojang/blaze3d/vertex/PoseStack.mapping
  data/com/mojang/blaze3d/vertex/SheetedDecalTextureGenerator.mapping
  data/com/mojang/blaze3d/vertex/VertexBuffer.mapping
  data/com/mojang/blaze3d/vertex/VertexConsumer.mapping
  data/com/mojang/blaze3d/vertex/VertexFormat.mapping
  data/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
  data/com/mojang/blaze3d/vertex/VertexMultiConsumer.mapping
  data/com/mojang/math/Matrix3f.mapping
  data/com/mojang/math/Matrix4f.mapping
  data/com/mojang/math/OctahedralGroup.mapping
  data/com/mojang/math/Quaternion.mapping
  data/com/mojang/math/SymmetricGroup3.mapping
  data/com/mojang/math/Transformation.mapping
  data/com/mojang/math/Vector3d.mapping
  data/com/mojang/math/Vector3f.mapping
  data/com/mojang/math/Vector4f.mapping
Labels: 1.17, mappings, parameters

#36 Remove standards and review docs from repo
  README.md
  docs/CONTRIBUTING.md
  docs/review-merge-process.md
  docs/standards.md
Labels: 1.17, meta

#27 Documented game events, potions, and enchantments.
  data/net/minecraft/world/item/alchemy/Potion.mapping
  data/net/minecraft/world/item/alchemy/Potions.mapping
  data/net/minecraft/world/item/enchantment/ArrowDamageEnchantment.mapping
  data/net/minecraft/world/item/enchantment/ArrowFireEnchantment.mapping
  data/net/minecraft/world/item/enchantment/ArrowInfiniteEnchantment.mapping
  data/net/minecraft/world/item/enchantment/ArrowKnockbackEnchantment.mapping
  data/net/minecraft/world/item/enchantment/ArrowPiercingEnchantment.mapping
  data/net/minecraft/world/item/enchantment/BindingCurseEnchantment.mapping
  data/net/minecraft/world/item/enchantment/DamageEnchantment.mapping
  data/net/minecraft/world/item/enchantment/DigDurabilityEnchantment.mapping
  data/net/minecraft/world/item/enchantment/DiggingEnchantment.mapping
  data/net/minecraft/world/item/enchantment/Enchantment.mapping
  data/net/minecraft/world/item/enchantment/EnchantmentInstance.mapping
  data/net/minecraft/world/item/enchantment/FireAspectEnchantment.mapping
  data/net/minecraft/world/item/enchantment/FrostWalkerEnchantment.mapping
  data/net/minecraft/world/item/enchantment/KnockbackEnchantment.mapping
  data/net/minecraft/world/item/enchantment/MendingEnchantment.mapping
  data/net/minecraft/world/item/enchantment/MultiShotEnchantment.mapping
  data/net/minecraft/world/item/enchantment/OxygenEnchantment.mapping
  data/net/minecraft/world/item/enchantment/ProtectionEnchantment.mapping
  data/net/minecraft/world/item/enchantment/QuickChargeEnchantment.mapping
  data/net/minecraft/world/item/enchantment/SoulSpeedEnchantment.mapping
  data/net/minecraft/world/item/enchantment/SweepingEdgeEnchantment.mapping
  data/net/minecraft/world/item/enchantment/ThornsEnchantment.mapping
  data/net/minecraft/world/item/enchantment/TridentChannelingEnchantment.mapping
  data/net/minecraft/world/item/enchantment/TridentImpalerEnchantment.mapping
  data/net/minecraft/world/item/enchantment/TridentLoyaltyEnchantment.mapping
  data/net/minecraft/world/item/enchantment/TridentRiptideEnchantment.mapping
  data/net/minecraft/world/item/enchantment/UntouchingEnchantment.mapping
  data/net/minecraft/world/item/enchantment/VanishingCurseEnchantment.mapping
  data/net/minecraft/world/item/enchantment/WaterWalkerEnchantment.mapping
  data/net/minecraft/world/item/enchantment/WaterWorkerEnchantment.mapping
  data/net/minecraft/world/level/gameevent/BlockPositionSource.mapping
  data/net/minecraft/world/level/gameevent/EntityPositionSource.mapping
  data/net/minecraft/world/level/gameevent/EuclideanGameEventDispatcher.mapping
  data/net/minecraft/world/level/gameevent/GameEvent.mapping
  data/net/minecraft/world/level/gameevent/GameEventDispatcher.mapping
  data/net/minecraft/world/level/gameevent/GameEventListener.mapping
  data/net/minecraft/world/level/gameevent/GameEventListenerRegistrar.mapping
  data/net/minecraft/world/level/gameevent/PositionSource.mapping
  data/net/minecraft/world/level/gameevent/PositionSourceType.mapping
  data/net/minecraft/world/level/material/MaterialColor.mapping
Labels: 1.17, javadocs, mappings, parameters

#39 Clean Up `net.minecraft.nbt`
  data/net/minecraft/nbt/ByteArrayTag.mapping
  data/net/minecraft/nbt/ByteTag.mapping
  data/net/minecraft/nbt/CompoundTag.mapping
  data/net/minecraft/nbt/DoubleTag.mapping
  data/net/minecraft/nbt/EndTag.mapping
  data/net/minecraft/nbt/FloatTag.mapping
  data/net/minecraft/nbt/IntArrayTag.mapping
  data/net/minecraft/nbt/IntTag.mapping
  data/net/minecraft/nbt/ListTag.mapping
  data/net/minecraft/nbt/LongArrayTag.mapping
  data/net/minecraft/nbt/LongTag.mapping
  data/net/minecraft/nbt/NbtAccounter.mapping
  data/net/minecraft/nbt/NbtIo.mapping
  data/net/minecraft/nbt/NbtOps.mapping
  data/net/minecraft/nbt/NbtUtils.mapping
  data/net/minecraft/nbt/ShortTag.mapping
  data/net/minecraft/nbt/SnbtPrinterTagVisitor.mapping
  data/net/minecraft/nbt/StringTag.mapping
  data/net/minecraft/nbt/StringTagVisitor.mapping
  data/net/minecraft/nbt/Tag.mapping
  data/net/minecraft/nbt/TagParser.mapping
  data/net/minecraft/nbt/TagVisitor.mapping
  data/net/minecraft/nbt/TextComponentTagVisitor.mapping
Labels: 1.17, javadocs, mappings, parameters

#43 Fix parameter name offsets in ClientboundCommandsPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundCommandsPacket.mapping
Labels: 1.17, bug, mappings, minor changes, parameters

#28 Maps net.minecraft.world.inventory
  data/net/minecraft/world/SimpleContainer.mapping
  data/net/minecraft/world/inventory/AbstractContainerMenu.mapping
  data/net/minecraft/world/inventory/AbstractFurnaceMenu.mapping
  data/net/minecraft/world/inventory/AnvilMenu.mapping
  data/net/minecraft/world/inventory/BeaconMenu.mapping
  data/net/minecraft/world/inventory/BlastFurnaceMenu.mapping
  data/net/minecraft/world/inventory/BrewingStandMenu.mapping
  data/net/minecraft/world/inventory/CartographyTableMenu.mapping
  data/net/minecraft/world/inventory/ChestMenu.mapping
  data/net/minecraft/world/inventory/ContainerLevelAccess.mapping
  data/net/minecraft/world/inventory/ContainerListener.mapping
  data/net/minecraft/world/inventory/CraftingContainer.mapping
  data/net/minecraft/world/inventory/CraftingMenu.mapping
  data/net/minecraft/world/inventory/DispenserMenu.mapping
  data/net/minecraft/world/inventory/EnchantmentMenu.mapping
  data/net/minecraft/world/inventory/FurnaceFuelSlot.mapping
  data/net/minecraft/world/inventory/FurnaceMenu.mapping
  data/net/minecraft/world/inventory/FurnaceResultSlot.mapping
  data/net/minecraft/world/inventory/GrindstoneMenu.mapping
  data/net/minecraft/world/inventory/HopperMenu.mapping
  data/net/minecraft/world/inventory/HorseInventoryMenu.mapping
  data/net/minecraft/world/inventory/InventoryMenu.mapping
  data/net/minecraft/world/inventory/ItemCombinerMenu.mapping
  data/net/minecraft/world/inventory/LecternMenu.mapping
  data/net/minecraft/world/inventory/LoomMenu.mapping
  data/net/minecraft/world/inventory/MenuConstructor.mapping
  data/net/minecraft/world/inventory/MenuType.mapping
  data/net/minecraft/world/inventory/MerchantContainer.mapping
  data/net/minecraft/world/inventory/MerchantMenu.mapping
  data/net/minecraft/world/inventory/MerchantResultSlot.mapping
  data/net/minecraft/world/inventory/PlayerEnderChestContainer.mapping
  data/net/minecraft/world/inventory/RecipeBookMenu.mapping
  data/net/minecraft/world/inventory/ResultSlot.mapping
  data/net/minecraft/world/inventory/ShulkerBoxMenu.mapping
  data/net/minecraft/world/inventory/SimpleContainerData.mapping
  data/net/minecraft/world/inventory/Slot.mapping
  data/net/minecraft/world/inventory/SmithingMenu.mapping
  data/net/minecraft/world/inventory/SmokerMenu.mapping
  data/net/minecraft/world/inventory/StonecutterMenu.mapping
Labels: 1.16.5, mappings, parameters

#44 Project phoenix: n/m/world/level/levelgen/carver
  data/net/minecraft/world/level/levelgen/carver/CanyonWorldCarver.mapping
  data/net/minecraft/world/level/levelgen/carver/CaveWorldCarver.mapping
  data/net/minecraft/world/level/levelgen/carver/ConfiguredWorldCarver.mapping
  data/net/minecraft/world/level/levelgen/carver/UnderwaterCaveWorldCarver.mapping
  data/net/minecraft/world/level/levelgen/carver/WorldCarver.mapping
Labels: 1.17, javadocs, mappings, parameters

#30 Some misc mappings
  data/net/minecraft/stats/RecipeBook.mapping
  data/net/minecraft/stats/RecipeBookSettings.mapping
  data/net/minecraft/stats/ServerStatsCounter.mapping
  data/net/minecraft/stats/Stat.mapping
  data/net/minecraft/stats/StatFormatter.mapping
  data/net/minecraft/stats/StatType.mapping
  data/net/minecraft/stats/StatsCounter.mapping
  data/net/minecraft/world/damagesource/BadRespawnPointDamage.mapping
  data/net/minecraft/world/damagesource/CombatEntry.mapping
  data/net/minecraft/world/damagesource/CombatTracker.mapping
  data/net/minecraft/world/damagesource/DamageSource.mapping
  data/net/minecraft/world/damagesource/EntityDamageSource.mapping
  data/net/minecraft/world/damagesource/IndirectEntityDamageSource.mapping
  data/net/minecraft/world/effect/AttackDamageMobEffect.mapping
  data/net/minecraft/world/effect/MobEffect.mapping
  data/net/minecraft/world/effect/MobEffectCategory.mapping
  data/net/minecraft/world/effect/MobEffectInstance.mapping
  data/net/minecraft/world/food/FoodProperties.mapping
  data/net/minecraft/world/food/Foods.mapping
  data/net/minecraft/world/scores/Objective.mapping
  data/net/minecraft/world/scores/PlayerTeam.mapping
  data/net/minecraft/world/scores/Score.mapping
  data/net/minecraft/world/scores/Scoreboard.mapping
  data/net/minecraft/world/scores/ScoreboardSaveData.mapping
  data/net/minecraft/world/scores/Team.mapping
  data/net/minecraft/world/scores/criteria/ObjectiveCriteria.mapping
Labels: 1.16.5, mappings, parameters

#42 Project Phoenix: net minecraft core
  data/net/minecraft/core/AxisCycle.mapping
  data/net/minecraft/core/BlockMath.mapping
  data/net/minecraft/core/BlockPos.mapping
  data/net/minecraft/core/BlockSource.mapping
  data/net/minecraft/core/BlockSourceImpl.mapping
  data/net/minecraft/core/Cursor3D.mapping
  data/net/minecraft/core/DefaultedRegistry.mapping
  data/net/minecraft/core/Direction.mapping
  data/net/minecraft/core/Direction8.mapping
  data/net/minecraft/core/FrontAndTop.mapping
  data/net/minecraft/core/IdMap.mapping
  data/net/minecraft/core/IdMapper.mapping
  data/net/minecraft/core/MappedRegistry.mapping
  data/net/minecraft/core/NonNullList.mapping
  data/net/minecraft/core/Registry.mapping
  data/net/minecraft/core/RegistryAccess.mapping
  data/net/minecraft/core/Rotations.mapping
  data/net/minecraft/core/SectionPos.mapping
  data/net/minecraft/core/SerializableUUID.mapping
  data/net/minecraft/core/Vec3i.mapping
  data/net/minecraft/core/WritableRegistry.mapping
Labels: 1.17, javadocs, mappings, parameters

#46 Mapped and Cleaned-Up: com.mojang.blaze3d, net.minecraft and some parts of net.minecraft.client
  data/com/mojang/blaze3d/Blaze3D.mapping
  data/com/mojang/blaze3d/audio/Channel.mapping
  data/com/mojang/blaze3d/audio/Library.mapping
  data/com/mojang/blaze3d/audio/OggAudioStream.mapping
  data/com/mojang/blaze3d/audio/OpenAlUtil.mapping
  data/com/mojang/blaze3d/font/TrueTypeGlyphProvider.mapping
  data/com/mojang/blaze3d/pipeline/MainTarget.mapping
  data/com/mojang/blaze3d/platform/GLX.mapping
  data/com/mojang/blaze3d/platform/GlDebug.mapping
  data/com/mojang/blaze3d/platform/GlStateManager.mapping
  data/com/mojang/blaze3d/platform/GlUtil.mapping
  data/com/mojang/blaze3d/platform/InputConstants.mapping
  data/com/mojang/blaze3d/platform/PngInfo.mapping
  data/com/mojang/blaze3d/platform/Window.mapping
  data/com/mojang/blaze3d/shaders/AbstractUniform.mapping
  data/com/mojang/blaze3d/shaders/EffectProgram.mapping
  data/com/mojang/blaze3d/shaders/Program.mapping
  data/com/mojang/blaze3d/shaders/Uniform.mapping
  data/com/mojang/blaze3d/systems/RenderSystem.mapping
  data/com/mojang/blaze3d/vertex/BufferBuilder.mapping
  data/com/mojang/blaze3d/vertex/BufferUploader.mapping
  data/com/mojang/blaze3d/vertex/PoseStack.mapping
  data/com/mojang/blaze3d/vertex/Tesselator.mapping
  data/com/mojang/blaze3d/vertex/VertexBuffer.mapping
  data/com/mojang/blaze3d/vertex/VertexFormat.mapping
  data/com/mojang/blaze3d/vertex/VertexMultiConsumer.mapping
  data/net/minecraft/BlockUtil.mapping
  data/net/minecraft/CharPredicate.mapping
  data/net/minecraft/ChatFormatting.mapping
  data/net/minecraft/CrashReport.mapping
  data/net/minecraft/CrashReportCategory.mapping
  data/net/minecraft/DefaultUncaughtExceptionHandler.mapping
  data/net/minecraft/DefaultUncaughtExceptionHandlerWithName.mapping
  data/net/minecraft/DetectedVersion.mapping
  data/net/minecraft/FileUtil.mapping
  data/net/minecraft/ReportedException.mapping
  data/net/minecraft/ResourceLocationException.mapping
  data/net/minecraft/SharedConstants.mapping
  data/net/minecraft/SystemReport.mapping
  data/net/minecraft/Util.mapping
  data/net/minecraft/client/gui/font/providers/TrueTypeGlyphProviderBuilder.mapping
Labels: 1.17.x, mappings, parameters

#47 Update from 1.17 to 1.17.1
  build.gradle
  data/com/mojang/blaze3d/platform/MemoryTracker.mapping
  data/net/minecraft/client/Screenshot.mapping
  data/net/minecraft/core/BlockPos.mapping
  data/net/minecraft/core/BlockSourceImpl.mapping
  data/net/minecraft/core/Direction.mapping
  data/net/minecraft/core/MappedRegistry.mapping
  data/net/minecraft/core/SectionPos.mapping
  data/net/minecraft/core/Vec3i.mapping
  data/net/minecraft/network/CompressionDecoder.mapping
  data/net/minecraft/network/Connection.mapping
  data/net/minecraft/network/protocol/game/ClientGamePacketListener.mapping
  data/net/minecraft/network/protocol/game/ClientboundContainerSetContentPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundContainerSetSlotPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundRemoveEntityPacket.mapping
  data/net/minecraft/network/protocol/game/ServerboundContainerClickPacket.mapping
  data/net/minecraft/network/protocol/game/ServerboundEditBookPacket.mapping
  data/net/minecraft/server/players/GameProfileCache.mapping
  data/net/minecraft/world/entity/LivingEntity.mapping
  data/net/minecraft/world/entity/boss/enderdragon/EnderDragon.mapping
  data/net/minecraft/world/entity/boss/wither/WitherBoss.mapping
  data/net/minecraft/world/inventory/AbstractContainerMenu.mapping
  data/net/minecraft/world/level/chunk/DataLayer.mapping
  data/net/minecraft/world/level/levelgen/WorldGenerationContext.mapping
  data/net/minecraft/world/level/levelgen/carver/CanyonWorldCarver.mapping
  data/net/minecraft/world/level/levelgen/carver/CarvingContext.mapping
  data/net/minecraft/world/level/levelgen/carver/CaveWorldCarver.mapping
  data/net/minecraft/world/level/levelgen/carver/WorldCarver.mapping
  data/net/minecraft/world/level/lighting/FlatDataLayer.mapping
Labels: 1.17.x, enhancement, mappings

#51 n/m/world/level/levelgen/surfacebuilders
  data/net/minecraft/world/level/levelgen/surfacebuilders/BadlandsSurfaceBuilder.mapping
  data/net/minecraft/world/level/levelgen/surfacebuilders/ConfiguredSurfaceBuilder.mapping
  data/net/minecraft/world/level/levelgen/surfacebuilders/DefaultSurfaceBuilder.mapping
  data/net/minecraft/world/level/levelgen/surfacebuilders/NetherCappedSurfaceBuilder.mapping
  data/net/minecraft/world/level/levelgen/surfacebuilders/NopeSurfaceBuilder.mapping
  data/net/minecraft/world/level/levelgen/surfacebuilders/SurfaceBuilder.mapping
  data/net/minecraft/world/level/levelgen/surfacebuilders/SurfaceBuilderBaseConfiguration.mapping
  data/net/minecraft/world/level/levelgen/surfacebuilders/SurfaceBuilderConfiguration.mapping
Labels: 1.17.x, mappings

#53 Added and updated various particle-related parameter mappings.
  data/net/minecraft/client/particle/AshParticle.mapping
  data/net/minecraft/client/particle/AttackSweepParticle.mapping
  data/net/minecraft/client/particle/BaseAshSmokeParticle.mapping
  data/net/minecraft/client/particle/BreakingItemParticle.mapping
  data/net/minecraft/client/particle/BubbleColumnUpParticle.mapping
  data/net/minecraft/client/particle/BubbleParticle.mapping
  data/net/minecraft/client/particle/BubblePopParticle.mapping
  data/net/minecraft/client/particle/CampfireSmokeParticle.mapping
  data/net/minecraft/client/particle/CritParticle.mapping
  data/net/minecraft/client/particle/DragonBreathParticle.mapping
  data/net/minecraft/client/particle/DripParticle.mapping
  data/net/minecraft/client/particle/DustColorTransitionParticle.mapping
  data/net/minecraft/client/particle/DustParticle.mapping
  data/net/minecraft/client/particle/DustParticleBase.mapping
  data/net/minecraft/client/particle/EnchantmentTableParticle.mapping
  data/net/minecraft/client/particle/EndRodParticle.mapping
  data/net/minecraft/client/particle/ExplodeParticle.mapping
  data/net/minecraft/client/particle/FallingDustParticle.mapping
  data/net/minecraft/client/particle/FireworkParticles.mapping
  data/net/minecraft/client/particle/FlameParticle.mapping
  data/net/minecraft/client/particle/GlowParticle.mapping
  data/net/minecraft/client/particle/HeartParticle.mapping
  data/net/minecraft/client/particle/HugeExplosionParticle.mapping
  data/net/minecraft/client/particle/ItemPickupParticle.mapping
  data/net/minecraft/client/particle/LargeSmokeParticle.mapping
  data/net/minecraft/client/particle/LavaParticle.mapping
  data/net/minecraft/client/particle/NoteParticle.mapping
  data/net/minecraft/client/particle/Particle.mapping
  data/net/minecraft/client/particle/ParticleDescription.mapping
  data/net/minecraft/client/particle/ParticleEngine.mapping
  data/net/minecraft/client/particle/ParticleRenderType.mapping
  data/net/minecraft/client/particle/PlayerCloudParticle.mapping
  data/net/minecraft/client/particle/ReversePortalParticle.mapping
  data/net/minecraft/client/particle/SimpleAnimatedParticle.mapping
  data/net/minecraft/client/particle/SmokeParticle.mapping
  data/net/minecraft/client/particle/SnowflakeParticle.mapping
  data/net/minecraft/client/particle/SoulParticle.mapping
  data/net/minecraft/client/particle/SpellParticle.mapping
  data/net/minecraft/client/particle/SpitParticle.mapping
  data/net/minecraft/client/particle/SplashParticle.mapping
  data/net/minecraft/client/particle/SpriteSet.mapping
  data/net/minecraft/client/particle/SquidInkParticle.mapping
  data/net/minecraft/client/particle/StationaryItemParticle.mapping
  data/net/minecraft/client/particle/SuspendedParticle.mapping
  data/net/minecraft/client/particle/SuspendedTownParticle.mapping
  data/net/minecraft/client/particle/TerrainParticle.mapping
  data/net/minecraft/client/particle/TotemParticle.mapping
  data/net/minecraft/client/particle/TrackingEmitter.mapping
  data/net/minecraft/client/particle/VibrationSignalParticle.mapping
  data/net/minecraft/client/particle/WakeParticle.mapping
  data/net/minecraft/client/particle/WaterCurrentDownParticle.mapping
  data/net/minecraft/client/particle/WaterDropParticle.mapping
  data/net/minecraft/client/particle/WhiteAshParticle.mapping
  data/net/minecraft/server/packs/metadata/pack/PackMetadataSection.mapping
  data/net/minecraft/server/packs/repository/PackCompatibility.mapping
  data/net/minecraft/world/phys/shapes/Shapes.mapping
Labels: 1.17.x, mappings
