Repository ParchmentMC/Parchment, pull requests merged in 2022-09, with the labels that each got.

#173 Fix: Incorrect argument name in net.minecraft.world.inventory.AbstractContainerMenu#clicked & doClick
  data/net/minecraft/world/inventory/AbstractContainerMenu.mapping
Labels: bug, mappings, minor changes, 1.18.x

#174 Fix javadoc @link tags
  data/net/minecraft/client/gui/MapRenderer.mapping
  data/net/minecraft/client/multiplayer/ClientPacketListener.mapping
  data/net/minecraft/client/renderer/blockentity/BannerRenderer.mapping
  data/net/minecraft/client/renderer/entity/ItemRenderer.mapping
  data/net/minecraft/network/protocol/PacketUtils.mapping
  data/net/minecraft/network/protocol/game/ClientGamePacketListener.mapping
  data/net/minecraft/network/protocol/game/ServerGamePacketListener.mapping
  data/net/minecraft/server/level/ChunkMap.mapping
  data/net/minecraft/server/network/ServerGamePacketListenerImpl.mapping
  data/net/minecraft/world/damagesource/CombatEntry.mapping
  data/net/minecraft/world/entity/Entity.mapping
  data/net/minecraft/world/entity/ai/goal/MoveToBlockGoal.mapping
  data/net/minecraft/world/entity/ai/navigation/PathNavigation.mapping
  data/net/minecraft/world/entity/animal/Rabbit.mapping
  data/net/minecraft/world/entity/item/FallingBlockEntity.mapping
  data/net/minecraft/world/entity/npc/Villager.mapping
  data/net/minecraft/world/entity/vehicle/MinecartCommandBlock.mapping
  data/net/minecraft/world/entity/vehicle/MinecartSpawner.mapping
  data/net/minecraft/world/item/Item.mapping
  data/net/minecraft/world/level/biome/BiomeManager.mapping
  data/net/minecraft/world/level/block/Block.mapping
  data/net/minecraft/world/level/block/state/BlockBehaviour.mapping
  data/net/minecraft/world/level/pathfinder/FlyNodeEvaluator.mapping
  data/net/minecraft/world/level/pathfinder/NodeEvaluator.mapping
  data/net/minecraft/world/level/pathfinder/WalkNodeEvaluator.mapping
Labels: bug, mappings, 1.19.x

#175 Fix: Incorrect argument name in net.minecraft.world.inventory.AbstractContainerMenu#clicked & doClick in 1.19 mappings
  data/net/minecraft/world/inventory/AbstractContainerMenu.mapping
Labels: bug, mappings, minor changes, 1.19.x

#177 Various mappings in net/minecraft/server
  data/net/minecraft/commands/arguments/MessageArgument.mapping
  data/net/minecraft/commands/arguments/ResourceKeyArgument.mapping
  data/net/minecraft/commands/arguments/item/ItemArgument.mapping
  data/net/minecraft/server/ServerFunctionManager.mapping
  data/net/minecraft/server/commands/LootCommand.mapping
  data/net/minecraft/server/dedicated/DedicatedServerProperties.mapping
  data/net/minecraft/server/dedicated/Settings.mapping
  data/net/minecraft/server/level/ServerPlayer.mapping
  data/net/minecraft/server/packs/FolderPackResources.mapping
  data/net/minecraft/server/packs/PackType.mapping
  data/net/minecraft/server/packs/ResourcePackFileNotFoundException.mapping
  data/net/minecraft/server/packs/VanillaPackResources.mapping
  data/net/minecraft/server/packs/repository/FolderRepositorySource.mapping
  data/net/minecraft/server/packs/repository/Pack.mapping
  data/net/minecraft/server/packs/repository/PackCompatibility.mapping
  data/net/minecraft/server/packs/resources/FallbackResourceManager.mapping
  data/net/minecraft/server/packs/resources/MultiPackResourceManager.mapping
  data/net/minecraft/server/packs/resources/ProfiledReloadInstance.mapping
  data/net/minecraft/server/packs/resources/ReloadableResourceManager.mapping
  data/net/minecraft/server/packs/resources/ResourceManager.mapping
  data/net/minecraft/server/packs/resources/SimpleJsonResourceReloadListener.mapping
  data/net/minecraft/server/packs/resources/SimpleReloadInstance.mapping
  data/net/minecraft/server/players/GameProfileCache.mapping
  data/net/minecraft/server/players/IpBanList.mapping
  data/net/minecraft/server/players/OldUsersConverter.mapping
  data/net/minecraft/server/players/PlayerList.mapping
Labels: mappings, 1.19.x
