Repository ParchmentMC/Parchment, pull requests merged in 2022-08, with the labels that each got.

#164 Update the game version in the readme
  README.md
Labels: bug, 1.19.x

#162 Various mappings in net/minecraft/world/entity
  data/net/minecraft/world/effect/MobEffectUtil.mapping
  data/net/minecraft/world/entity/ai/behavior/warden/SetRoarTarget.mapping
  data/net/minecraft/world/entity/ai/behavior/warden/SonicBoom.mapping
  data/net/minecraft/world/entity/animal/allay/Allay.mapping
  data/net/minecraft/world/entity/animal/allay/AllayAi.mapping
  data/net/minecraft/world/entity/animal/frog/Frog.mapping
  data/net/minecraft/world/entity/animal/frog/FrogAi.mapping
  data/net/minecraft/world/entity/animal/frog/ShootTongue.mapping
  data/net/minecraft/world/entity/animal/frog/Tadpole.mapping
  data/net/minecraft/world/entity/animal/frog/TadpoleAi.mapping
  data/net/minecraft/world/entity/monster/warden/AngerLevel.mapping
  data/net/minecraft/world/entity/monster/warden/AngerManagement.mapping
  data/net/minecraft/world/entity/monster/warden/Warden.mapping
  data/net/minecraft/world/entity/monster/warden/WardenAi.mapping
  data/net/minecraft/world/entity/monster/warden/WardenSpawnTracker.mapping
  data/net/minecraft/world/level/pathfinder/PathFinder.mapping
Labels: mappings, 1.19.x

#163 Various mappings for net/minecraft/client
  data/net/minecraft/client/GuiMessageTag.mapping
  data/net/minecraft/client/OptionInstance.mapping
  data/net/minecraft/client/StringSplitter.mapping
  data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
  data/net/minecraft/client/gui/components/PlayerFaceRenderer.mapping
  data/net/minecraft/client/gui/screens/BanNoticeScreen.mapping
  data/net/minecraft/client/gui/screens/ChatScreen.mapping
  data/net/minecraft/client/gui/screens/ConfirmLinkScreen.mapping
  data/net/minecraft/client/gui/screens/ConfirmScreen.mapping
  data/net/minecraft/client/gui/screens/GenericWaitingScreen.mapping
  data/net/minecraft/client/gui/screens/multiplayer/WarningScreen.mapping
  data/net/minecraft/client/gui/screens/reporting/ChatLogSegmenter.mapping
  data/net/minecraft/client/gui/screens/reporting/ChatReportScreen.mapping
  data/net/minecraft/client/gui/screens/reporting/ChatSelectionLogFiller.mapping
  data/net/minecraft/client/gui/screens/reporting/ChatSelectionScreen.mapping
  data/net/minecraft/client/gui/screens/reporting/ReportReasonSelectionScreen.mapping
  data/net/minecraft/client/gui/screens/worldselection/WorldOpenFlows.mapping
  data/net/minecraft/client/player/LocalPlayer.mapping
  data/net/minecraft/client/renderer/entity/layers/WardenEmissiveLayer.mapping
  data/net/minecraft/client/renderer/item/CompassItemPropertyFunction.mapping
  data/net/minecraft/client/resources/SkinManager.mapping
  data/net/minecraft/network/chat/ChatMessageContent.mapping
  data/net/minecraft/network/chat/PreviewableCommand.mapping
Labels: mappings, 1.19.x

#165 Various mappings in net/minecraft/server and net/minecraft/network
  data/net/minecraft/network/chat/FilterMask.mapping
  data/net/minecraft/network/chat/LastSeenMessages.mapping
  data/net/minecraft/network/chat/MessageSignature.mapping
  data/net/minecraft/network/protocol/game/ClientboundBlockChangedAckPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundChatPreviewPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundCommandsPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundCustomChatCompletionsPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundDeleteChatPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundLevelChunkWithLightPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundLightUpdatePacketData.mapping
  data/net/minecraft/network/protocol/game/ClientboundPlayerChatHeaderPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundPlayerChatPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundServerDataPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundSetDisplayChatPreviewPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundSystemChatPacket.mapping
  data/net/minecraft/network/protocol/game/ServerGamePacketListener.mapping
  data/net/minecraft/network/protocol/game/ServerboundChatAckPacket.mapping
  data/net/minecraft/network/protocol/game/ServerboundChatCommandPacket.mapping
  data/net/minecraft/network/protocol/game/ServerboundChatPacket.mapping
  data/net/minecraft/network/protocol/game/ServerboundChatPreviewPacket.mapping
  data/net/minecraft/network/protocol/game/ServerboundInteractPacket.mapping
  data/net/minecraft/network/protocol/game/ServerboundPlayerActionPacket.mapping
  data/net/minecraft/server/Main.mapping
  data/net/minecraft/server/MinecraftServer.mapping
  data/net/minecraft/server/commands/PlaceCommand.mapping
  data/net/minecraft/server/network/ServerGamePacketListenerImpl.mapping
  data/net/minecraft/server/network/TextFilterClient.mapping
  data/net/minecraft/util/worldupdate/WorldUpgrader.mapping
Labels: mappings, 1.19.x

#161 Various mappings in net/minecraft/client/multiplayer
  data/net/minecraft/client/multiplayer/ClientLevel.mapping
  data/net/minecraft/client/multiplayer/ClientPacketListener.mapping
  data/net/minecraft/client/multiplayer/ClientSuggestionProvider.mapping
  data/net/minecraft/client/multiplayer/MultiPlayerGameMode.mapping
  data/net/minecraft/client/multiplayer/ProfileKeyPairManager.mapping
  data/net/minecraft/client/multiplayer/ServerData.mapping
  data/net/minecraft/client/multiplayer/ServerStatusPinger.mapping
  data/net/minecraft/client/multiplayer/chat/ChatListener.mapping
  data/net/minecraft/client/multiplayer/chat/ChatLog.mapping
  data/net/minecraft/client/multiplayer/chat/ChatPreviewStatus.mapping
  data/net/minecraft/client/multiplayer/chat/ChatTrustLevel.mapping
  data/net/minecraft/client/multiplayer/chat/LoggedChatMessage.mapping
  data/net/minecraft/client/multiplayer/chat/LoggedChatMessageLink.mapping
  data/net/minecraft/client/multiplayer/chat/RollingMemoryChatLog.mapping
  data/net/minecraft/client/multiplayer/chat/report/AbuseReportSender.mapping
  data/net/minecraft/client/multiplayer/chat/report/ChatReportBuilder.mapping
  data/net/minecraft/client/multiplayer/chat/report/ReportEnvironment.mapping
  data/net/minecraft/client/multiplayer/chat/report/ReportReason.mapping
  data/net/minecraft/client/multiplayer/chat/report/ReportingContext.mapping
  data/net/minecraft/client/multiplayer/prediction/BlockStatePredictionHandler.mapping
Labels: mappings, 1.19.x

#166 Various mappings in net/minecraft/network/chat
  data/net/minecraft/network/chat/ChatPreviewCache.mapping
  data/net/minecraft/network/chat/ChatPreviewThrottler.mapping
  data/net/minecraft/network/chat/ChatTypeDecoration.mapping
  data/net/minecraft/network/chat/CommonComponents.mapping
  data/net/minecraft/network/chat/ComponentUtils.mapping
  data/net/minecraft/network/chat/FilterMask.mapping
  data/net/minecraft/network/chat/LastSeenMessages.mapping
  data/net/minecraft/network/chat/LastSeenMessagesTracker.mapping
  data/net/minecraft/network/chat/LastSeenMessagesValidator.mapping
  data/net/minecraft/network/chat/MessageSigner.mapping
  data/net/minecraft/network/chat/MutableComponent.mapping
  data/net/minecraft/network/chat/OutgoingPlayerChatMessage.mapping
  data/net/minecraft/network/chat/PlayerChatMessage.mapping
  data/net/minecraft/network/chat/PreviewableCommand.mapping
  data/net/minecraft/network/chat/SignedMessageBody.mapping
  data/net/minecraft/network/chat/SignedMessageChain.mapping
  data/net/minecraft/network/chat/SignedMessageHeader.mapping
  data/net/minecraft/network/chat/SignedMessageValidator.mapping
  data/net/minecraft/network/chat/Style.mapping
  data/net/minecraft/network/chat/ThrowingComponent.mapping
  data/net/minecraft/network/chat/contents/BlockDataSource.mapping
  data/net/minecraft/network/chat/contents/DataSource.mapping
  data/net/minecraft/network/chat/contents/EntityDataSource.mapping
  data/net/minecraft/network/chat/contents/KeybindResolver.mapping
Labels: ready to merge, mappings, 1.19.x

#167 Various mappings in net/minecraft/world/level
  data/net/minecraft/world/level/block/DropExperienceBlock.mapping
  data/net/minecraft/world/level/block/FrogspawnBlock.mapping
  data/net/minecraft/world/level/block/GrowingPlantBodyBlock.mapping
  data/net/minecraft/world/level/block/MangrovePropaguleBlock.mapping
  data/net/minecraft/world/level/block/MultifaceSpreader.mapping
  data/net/minecraft/world/level/block/SculkBehaviour.mapping
  data/net/minecraft/world/level/block/SculkBlock.mapping
  data/net/minecraft/world/level/block/SculkCatalystBlock.mapping
  data/net/minecraft/world/level/block/SculkSpreader.mapping
  data/net/minecraft/world/level/block/SculkVeinBlock.mapping
  data/net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/BannerPatterns.mapping
  data/net/minecraft/world/level/block/entity/DispenserBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/JukeboxBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/SculkCatalystBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/SculkShriekerBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/StructureBlockEntity.mapping
  data/net/minecraft/world/level/block/grower/MangroveTreeGrower.mapping
  data/net/minecraft/world/level/block/state/BlockBehaviour.mapping
  data/net/minecraft/world/level/levelgen/feature/FeatureCountTracker.mapping
  data/net/minecraft/world/level/levelgen/feature/MultifaceGrowthFeature.mapping
  data/net/minecraft/world/level/levelgen/feature/RootSystemFeature.mapping
  data/net/minecraft/world/level/levelgen/feature/SculkPatchFeature.mapping
  data/net/minecraft/world/level/levelgen/feature/configurations/MultifaceGrowthConfiguration.mapping
  data/net/minecraft/world/level/levelgen/feature/rootplacers/MangroveRootPlacer.mapping
  data/net/minecraft/world/level/levelgen/feature/rootplacers/RootPlacer.mapping
  data/net/minecraft/world/level/levelgen/feature/rootplacers/RootPlacerType.mapping
  data/net/minecraft/world/level/levelgen/feature/stateproviders/NoiseBasedStateProvider.mapping
  data/net/minecraft/world/level/levelgen/feature/stateproviders/NoiseProvider.mapping
  data/net/minecraft/world/level/levelgen/feature/stateproviders/RuleBasedBlockStateProvider.mapping
  data/net/minecraft/world/level/levelgen/feature/treedecorators/AttachedToLeavesDecorator.mapping
  data/net/minecraft/world/level/levelgen/feature/trunkplacers/UpwardsBranchingTrunkPlacer.mapping
  data/net/minecraft/world/level/levelgen/structure/SinglePieceStructure.mapping
  data/net/minecraft/world/level/levelgen/structure/Structure.mapping
  data/net/minecraft/world/level/levelgen/structure/StructureCheck.mapping
  data/net/minecraft/world/level/levelgen/structure/placement/StructurePlacement.mapping
  data/net/minecraft/world/level/levelgen/structure/pools/JigsawPlacement.mapping
Labels: mappings, 1.19.x

#169 New 1.19.2 Mappings & Better Readme
  data/net/minecraft/client/gui/screens/AccessibilityOptionsScreen.mapping
  data/net/minecraft/client/gui/screens/ChatScreen.mapping
  data/net/minecraft/client/gui/screens/MouseSettingsScreen.mapping
  data/net/minecraft/client/gui/screens/PauseScreen.mapping
  data/net/minecraft/client/gui/screens/TitleScreen.mapping
  data/net/minecraft/client/gui/screens/VideoSettingsScreen.mapping
  data/net/minecraft/client/particle/BlockMarker.mapping
  data/net/minecraft/client/particle/NoteParticle.mapping
  data/net/minecraft/client/particle/ParticleEngine.mapping
  data/net/minecraft/client/particle/PortalParticle.mapping
  data/net/minecraft/client/particle/SculkChargeParticle.mapping
  data/net/minecraft/client/particle/SculkChargePopParticle.mapping
  data/net/minecraft/client/particle/ShriekParticle.mapping
  data/net/minecraft/client/particle/SonicBoomParticle.mapping
  data/net/minecraft/client/particle/SoulParticle.mapping
  data/net/minecraft/client/renderer/FogRenderer.mapping
  data/net/minecraft/client/renderer/GameRenderer.mapping
  data/net/minecraft/client/renderer/LevelRenderer.mapping
  data/net/minecraft/client/renderer/LightTexture.mapping
  data/net/minecraft/client/renderer/RenderType.mapping
  data/net/minecraft/util/profiling/metrics/MetricsSamplerProvider.mapping
Labels: mappings, 1.19.x

#171 Fixing typo
  data/net/minecraft/network/chat/Component.mapping
Labels: bug, mappings, 1.19.x
