Repository ParchmentMC/Parchment, pull requests merged in 2022-11, with the labels that each got.

#183 Two backports and some net/minecraft/server mappings
  data/net/minecraft/Util.mapping
  data/net/minecraft/server/ConsoleInput.mapping
  data/net/minecraft/server/MinecraftServer.mapping
  data/net/minecraft/server/dedicated/DedicatedServer.mapping
  data/net/minecraft/server/dedicated/DedicatedServerProperties.mapping
  data/net/minecraft/server/dedicated/Settings.mapping
  data/net/minecraft/server/level/progress/ChunkProgressListenerFactory.mapping
  data/net/minecraft/server/packs/AbstractPackResources.mapping
  data/net/minecraft/server/packs/FolderPackResources.mapping
  data/net/minecraft/server/packs/ResourcePackFileNotFoundException.mapping
  data/net/minecraft/server/packs/VanillaPackResources.mapping
  data/net/minecraft/server/packs/resources/FallbackResourceManager.mapping
  data/net/minecraft/server/packs/resources/MultiPackResourceManager.mapping
  data/net/minecraft/server/packs/resources/ProfiledReloadInstance.mapping
  data/net/minecraft/server/packs/resources/ReloadableResourceManager.mapping
  data/net/minecraft/server/packs/resources/SimpleJsonResourceReloadListener.mapping
  data/net/minecraft/server/packs/resources/SimpleReloadInstance.mapping
  data/net/minecraft/server/packs/resources/SimpleResource.mapping
  data/net/minecraft/server/players/GameProfileCache.mapping
  data/net/minecraft/server/players/IpBanList.mapping
  data/net/minecraft/server/players/OldUsersConverter.mapping
  data/net/minecraft/server/players/PlayerList.mapping
  data/net/minecraft/server/rcon/PktUtils.mapping
  data/net/minecraft/server/rcon/thread/GenericThread.mapping
  data/net/minecraft/server/rcon/thread/QueryThreadGs4.mapping
  data/net/minecraft/server/rcon/thread/RconClient.mapping
  data/net/minecraft/server/rcon/thread/RconThread.mapping
  data/net/minecraft/world/ticks/LevelTickAccess.mapping
  data/net/minecraft/world/ticks/LevelTicks.mapping
  data/net/minecraft/world/ticks/ProtoChunkTicks.mapping
  data/net/minecraft/world/ticks/SavedTick.mapping
  data/net/minecraft/world/ticks/ScheduledTick.mapping
  data/net/minecraft/world/ticks/TickAccess.mapping
Labels: mappings, 1.18.x

#188 [1.18] Fix param names of VineBlock#isAcceptableNeighbor
  data/net/minecraft/world/level/block/VineBlock.mapping
Labels: bug, mappings, minor changes, 1.18.x

#187 [1.18] Remove javadoc for ServerPlayer#drop
  data/net/minecraft/server/level/ServerPlayer.mapping
Labels: bug, mappings, minor changes, 1.18.x

#186 [1.19] Fix param names of VineBlock#isAcceptableNeighbor
  data/net/minecraft/world/level/block/VineBlock.mapping
Labels: bug, mappings, minor changes, 1.19.x

#185 [1.19] Remove javadoc for ServerPlayer#drop
  data/net/minecraft/server/level/ServerPlayer.mapping
Labels: bug, mappings, minor changes, 1.19.x

#189 Various mapping in net/minecraft/server
  data/net/minecraft/server/ConsoleInput.mapping
  data/net/minecraft/server/MinecraftServer.mapping
  data/net/minecraft/server/dedicated/DedicatedServer.mapping
  data/net/minecraft/server/dedicated/DedicatedServerProperties.mapping
  data/net/minecraft/server/dedicated/Settings.mapping
  data/net/minecraft/server/level/ChunkMap.mapping
  data/net/minecraft/server/level/ServerPlayer.mapping
  data/net/minecraft/server/level/progress/ChunkProgressListenerFactory.mapping
  data/net/minecraft/server/packs/FolderPackResources.mapping
  data/net/minecraft/server/packs/VanillaPackResources.mapping
  data/net/minecraft/server/packs/resources/SimpleReloadInstance.mapping
  data/net/minecraft/server/players/GameProfileCache.mapping
  data/net/minecraft/server/rcon/PktUtils.mapping
  data/net/minecraft/server/rcon/thread/GenericThread.mapping
  data/net/minecraft/server/rcon/thread/QueryThreadGs4.mapping
  data/net/minecraft/server/rcon/thread/RconClient.mapping
  data/net/minecraft/server/rcon/thread/RconThread.mapping
  data/net/minecraft/world/entity/player/Inventory.mapping
Labels: mappings, 1.19.x

#190 Various mappings in net/minecraft/world/entity
  data/net/minecraft/world/effect/MobEffectUtil.mapping
  data/net/minecraft/world/entity/AgeableMob.mapping
  data/net/minecraft/world/entity/Entity.mapping
  data/net/minecraft/world/entity/LightningBolt.mapping
  data/net/minecraft/world/entity/LivingEntity.mapping
  data/net/minecraft/world/entity/Mob.mapping
  data/net/minecraft/world/entity/ai/behavior/AcquirePoi.mapping
  data/net/minecraft/world/entity/ai/behavior/InteractWith.mapping
  data/net/minecraft/world/entity/ai/behavior/InteractWithDoor.mapping
  data/net/minecraft/world/entity/ai/behavior/JumpOnBed.mapping
  data/net/minecraft/world/entity/ai/behavior/LongJumpToRandomPos.mapping
  data/net/minecraft/world/entity/ai/behavior/Mount.mapping
  data/net/minecraft/world/entity/ai/behavior/MoveToSkySeeingSpot.mapping
  data/net/minecraft/world/entity/ai/behavior/ShowTradesToPlayer.mapping
  data/net/minecraft/world/entity/ai/behavior/StartAttacking.mapping
  data/net/minecraft/world/entity/animal/frog/Frog.mapping
  data/net/minecraft/world/entity/decoration/ItemFrame.mapping
  data/net/minecraft/world/entity/decoration/Painting.mapping
  data/net/minecraft/world/entity/monster/warden/Warden.mapping
  data/net/minecraft/world/entity/npc/InventoryCarrier.mapping
  data/net/minecraft/world/entity/npc/VillagerProfession.mapping
  data/net/minecraft/world/entity/player/Inventory.mapping
  data/net/minecraft/world/entity/player/Player.mapping
  data/net/minecraft/world/entity/raid/Raids.mapping
  data/net/minecraft/world/entity/vehicle/ContainerEntity.mapping
Labels: mappings, 1.19.x
