Repository ParchmentMC/Parchment, pull requests merged in 2023-06, with the labels that each got.

#200 redstone signal javadocs and related refactors
  data/net/minecraft/world/level/Level.mapping
  data/net/minecraft/world/level/LevelReader.mapping
  data/net/minecraft/world/level/block/BasePressurePlateBlock.mapping
  data/net/minecraft/world/level/block/BaseRailBlock.mapping
  data/net/minecraft/world/level/block/DetectorRailBlock.mapping
  data/net/minecraft/world/level/block/DiodeBlock.mapping
  data/net/minecraft/world/level/block/RailState.mapping
  data/net/minecraft/world/level/block/RedStoneWireBlock.mapping
  data/net/minecraft/world/level/block/RedstoneTorchBlock.mapping
  data/net/minecraft/world/level/block/TripWireHookBlock.mapping
  data/net/minecraft/world/level/block/piston/PistonBaseBlock.mapping
  data/net/minecraft/world/level/block/state/BlockBehaviour.mapping
  data/net/minecraft/world/level/redstone/NeighborUpdater.mapping
Labels: mappings, 1.19.x

#202 redstone signal javadocs and related refactors (1.20 edition)
  data/net/minecraft/world/level/Level.mapping
  data/net/minecraft/world/level/SignalGetter.mapping
  data/net/minecraft/world/level/block/DiodeBlock.mapping
  data/net/minecraft/world/level/block/state/BlockBehaviour.mapping
Labels: mappings, 1.20.x

#203 [1.20] Miscellaneous mappings
  data/net/minecraft/client/tutorial/FindTreeTutorialStepInstance.mapping
  data/net/minecraft/core/DefaultedMappedRegistry.mapping
  data/net/minecraft/core/HolderGetter.mapping
  data/net/minecraft/core/HolderLookup.mapping
  data/net/minecraft/core/LayeredRegistryAccess.mapping
  data/net/minecraft/core/MappedRegistry.mapping
  data/net/minecraft/core/RegistrySetBuilder.mapping
  data/net/minecraft/core/RegistrySynchronization.mapping
  data/net/minecraft/core/dispenser/BoatDispenseItemBehavior.mapping
  data/net/minecraft/core/registries/BuiltInRegistries.mapping
  data/net/minecraft/data/BlockFamily.mapping
  data/net/minecraft/data/DataProvider.mapping
  data/net/minecraft/data/metadata/PackMetadataGenerator.mapping
  data/net/minecraft/gametest/framework/AfterBatch.mapping
  data/net/minecraft/gametest/framework/BeforeBatch.mapping
  data/net/minecraft/gametest/framework/GameTestRegistry.mapping
  data/net/minecraft/gametest/framework/TestClassNameArgument.mapping
  data/net/minecraft/gametest/framework/TestFunctionArgument.mapping
  data/net/minecraft/network/chat/LastSeenMessages.mapping
  data/net/minecraft/network/chat/LastSeenMessagesTracker.mapping
  data/net/minecraft/network/chat/LastSeenMessagesValidator.mapping
  data/net/minecraft/network/protocol/login/ServerboundKeyPacket.mapping
  data/net/minecraft/network/syncher/EntityDataSerializer.mapping
  data/net/minecraft/resources/RegistryDataLoader.mapping
  data/net/minecraft/resources/RegistryFixedCodec.mapping
  data/net/minecraft/resources/RegistryOps.mapping
  data/net/minecraft/resources/ResourceLocation.mapping
  data/net/minecraft/server/Bootstrap.mapping
  data/net/minecraft/server/ChainedJsonException.mapping
  data/net/minecraft/server/ServerScoreboard.mapping
  data/net/minecraft/server/TickTask.mapping
  data/net/minecraft/server/WorldLoader.mapping
  data/net/minecraft/server/bossevents/CustomBossEvents.mapping
  data/net/minecraft/server/chase/ChaseClient.mapping
  data/net/minecraft/server/commands/LootCommand.mapping
  data/net/minecraft/server/dedicated/DedicatedServer.mapping
  data/net/minecraft/server/dedicated/DedicatedServerSettings.mapping
  data/net/minecraft/server/dedicated/Settings.mapping
  data/net/minecraft/server/level/DistanceManager.mapping
  data/net/minecraft/server/level/TickingTracker.mapping
  data/net/minecraft/server/level/WorldGenRegion.mapping
  data/net/minecraft/server/packs/repository/BuiltInPackSource.mapping
  data/net/minecraft/server/packs/repository/FolderRepositorySource.mapping
  data/net/minecraft/world/item/AdventureModeCheck.mapping
  data/net/minecraft/world/item/trading/MerchantOffers.mapping
  data/net/minecraft/world/level/chunk/storage/ChunkStorage.mapping
  data/net/minecraft/world/ticks/LevelChunkTicks.mapping
  data/net/minecraft/world/ticks/LevelTickAccess.mapping
  data/net/minecraft/world/ticks/ScheduledTick.mapping
  data/net/minecraft/world/ticks/TickAccess.mapping
Labels: mappings, 1.20.x

#204 Update to Gradle 8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: enhancement, 1.20.x

#206 Map some parameters in the realmsclient package
  data/com/mojang/realmsclient/client/FileDownload.mapping
  data/com/mojang/realmsclient/client/FileUpload.mapping
  data/com/mojang/realmsclient/client/Request.mapping
  data/com/mojang/realmsclient/gui/RealmsWorldSlotButton.mapping
  data/com/mojang/realmsclient/gui/RowButton.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsBackupScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsSlotOptionsScreen.mapping
  data/com/mojang/realmsclient/util/LevelType.mapping
  data/com/mojang/realmsclient/util/RealmsTextureManager.mapping
  data/com/mojang/realmsclient/util/RealmsUtil.mapping
  data/com/mojang/realmsclient/util/TextRenderingUtils.mapping
Labels: mappings, 1.20.x

#205 Add some blaze3d and com.mojang.math mappings
  data/com/mojang/blaze3d/font/GlyphInfo.mapping
  data/com/mojang/blaze3d/platform/MacosUtil.mapping
  data/com/mojang/blaze3d/shaders/FogShape.mapping
  data/com/mojang/math/Axis.mapping
Labels: mappings, minor changes, 1.20.x

#207 Map classes in net.minecraft.util
  data/net/minecraft/util/BitStorage.mapping
  data/net/minecraft/util/Brightness.mapping
  data/net/minecraft/util/ClassInstanceMultiMap.mapping
  data/net/minecraft/util/CrudeIncrementalIntIdentityHashBiMap.mapping
  data/net/minecraft/util/Crypt.mapping
  data/net/minecraft/util/CsvOutput.mapping
  data/net/minecraft/util/CubicSampler.mapping
  data/net/minecraft/util/CubicSpline.mapping
  data/net/minecraft/util/FastBufferedInputStream.mapping
  data/net/minecraft/util/FrameTimer.mapping
  data/net/minecraft/util/HttpUtil.mapping
  data/net/minecraft/util/InclusiveRange.mapping
  data/net/minecraft/util/LazyLoadedValue.mapping
  data/net/minecraft/util/Mth.mapping
  data/net/minecraft/util/NativeModuleLister.mapping
  data/net/minecraft/util/SignatureValidator.mapping
  data/net/minecraft/util/SortedArraySet.mapping
  data/net/minecraft/util/SpawnUtil.mapping
  data/net/minecraft/util/StringRepresentable.mapping
  data/net/minecraft/util/StringUtil.mapping
  data/net/minecraft/util/TaskChainer.mapping
  data/net/minecraft/util/ThreadingDetector.mapping
  data/net/minecraft/util/ToFloatFunction.mapping
  data/net/minecraft/util/eventlog/EventLogDirectory.mapping
  data/net/minecraft/util/monitoring/jmx/MinecraftServerStatistics.mapping
  data/net/minecraft/util/thread/NamedThreadFactory.mapping
Labels: mappings, 1.20.x
