Repository ParchmentMC/Parchment, pull requests merged in 2023-08, with the labels that each got.

#238 Fix inconsistent parameter in `ResourceLocation$Serializer`
  data/net/minecraft/resources/ResourceLocation.mapping
Labels: bug, mappings, minor changes, 1.20.x

#218 Render Code - Mappings & JavaDocs
  data/net/minecraft/client/gui/ComponentPath.mapping
  data/net/minecraft/client/gui/Gui.mapping
  data/net/minecraft/client/gui/GuiGraphics.mapping
  data/net/minecraft/client/gui/components/Renderable.mapping
  data/net/minecraft/client/gui/components/TabOrderedElement.mapping
  data/net/minecraft/client/gui/components/events/ContainerEventHandler.mapping
  data/net/minecraft/client/gui/components/events/GuiEventListener.mapping
  data/net/minecraft/client/gui/components/tabs/TabNavigationBar.mapping
  data/net/minecraft/client/gui/narration/NarratableEntry.mapping
  data/net/minecraft/client/gui/narration/NarrationSupplier.mapping
Labels: mappings, 1.20.x

#240 finish mapping world.level.storage
  data/net/minecraft/world/level/storage/CommandStorage.mapping
  data/net/minecraft/world/level/storage/DimensionDataStorage.mapping
  data/net/minecraft/world/level/storage/LevelStorageSource.mapping
  data/net/minecraft/world/level/storage/LevelSummary.mapping
  data/net/minecraft/world/level/storage/PrimaryLevelData.mapping
Labels: mappings, 1.20.x

#236 finish params for world.level.storage.loot.parameters
  data/net/minecraft/world/level/storage/loot/parameters/LootContextParamSet.mapping
  data/net/minecraft/world/level/storage/loot/parameters/LootContextParamSets.mapping
Labels: mappings, 1.20.x

#235 finish params for world.level.storage.loot.predicates
  data/net/minecraft/world/level/storage/loot/predicates/BonusLevelTableCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/CompositeLootItemCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/ConditionReference.mapping
  data/net/minecraft/world/level/storage/loot/predicates/ConditionUserBuilder.mapping
  data/net/minecraft/world/level/storage/loot/predicates/DamageSourceCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/EntityHasScoreCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/ExplosionCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/InvertedLootItemCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/LocationCheck.mapping
  data/net/minecraft/world/level/storage/loot/predicates/LootItemBlockStatePropertyCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/LootItemConditions.mapping
  data/net/minecraft/world/level/storage/loot/predicates/LootItemEntityPropertyCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/LootItemKilledByPlayerCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/LootItemRandomChanceCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/LootItemRandomChanceWithLootingCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/MatchTool.mapping
  data/net/minecraft/world/level/storage/loot/predicates/TimeCheck.mapping
  data/net/minecraft/world/level/storage/loot/predicates/ValueCheckCondition.mapping
  data/net/minecraft/world/level/storage/loot/predicates/WeatherCheck.mapping
Labels: mappings, 1.20.x

#234 finish params for world.level.storage.loot.functions
  data/net/minecraft/world/level/storage/loot/functions/ApplyBonusCount.mapping
  data/net/minecraft/world/level/storage/loot/functions/CopyBlockState.mapping
  data/net/minecraft/world/level/storage/loot/functions/CopyNameFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/CopyNbtFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/EnchantRandomlyFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/EnchantWithLevelsFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/ExplorationMapFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/FillPlayerHead.mapping
  data/net/minecraft/world/level/storage/loot/functions/FunctionReference.mapping
  data/net/minecraft/world/level/storage/loot/functions/FunctionUserBuilder.mapping
  data/net/minecraft/world/level/storage/loot/functions/LimitCount.mapping
  data/net/minecraft/world/level/storage/loot/functions/LootItemConditionalFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/LootItemFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/LootItemFunctions.mapping
  data/net/minecraft/world/level/storage/loot/functions/LootingEnchantFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetAttributesFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetBannerPatternFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetContainerContents.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetContainerLootTable.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetEnchantmentsFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetInstrumentFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetItemCountFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetItemDamageFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetLoreFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetNameFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetNbtFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetPotionFunction.mapping
  data/net/minecraft/world/level/storage/loot/functions/SetStewEffectFunction.mapping
Labels: mappings, 1.20.x

#243 finish mapping world/level/biome
  data/net/minecraft/world/level/biome/Biome.mapping
  data/net/minecraft/world/level/biome/BiomeGenerationSettings.mapping
  data/net/minecraft/world/level/biome/BiomeSource.mapping
  data/net/minecraft/world/level/biome/Climate.mapping
  data/net/minecraft/world/level/biome/FeatureSorter.mapping
  data/net/minecraft/world/level/biome/MobSpawnSettings.mapping
  data/net/minecraft/world/level/biome/MultiNoiseBiomeSource.mapping
  data/net/minecraft/world/level/biome/MultiNoiseBiomeSourceParameterList.mapping
  data/net/minecraft/world/level/biome/OverworldBiomeBuilder.mapping
  data/net/minecraft/world/level/biome/TheEndBiomeSource.mapping
Labels: mappings, 1.20.x

#237 The rest of the world.level.storage.loot package
  data/net/minecraft/world/level/storage/loot/IntRange.mapping
  data/net/minecraft/world/level/storage/loot/LootDataManager.mapping
  data/net/minecraft/world/level/storage/loot/LootDataType.mapping
  data/net/minecraft/world/level/storage/loot/LootPool.mapping
  data/net/minecraft/world/level/storage/loot/LootTable.mapping
  data/net/minecraft/world/level/storage/loot/entries/AlternativesEntry.mapping
  data/net/minecraft/world/level/storage/loot/entries/LootTableReference.mapping
  data/net/minecraft/world/level/storage/loot/entries/TagEntry.mapping
Labels: mappings, 1.20.x

#249 finish mapping world/level/dimension/ & world/level/entity/
  data/net/minecraft/world/level/dimension/DimensionType.mapping
  data/net/minecraft/world/level/dimension/end/EndDragonFight.mapping
  data/net/minecraft/world/level/entity/PersistentEntitySectionManager.mapping
  data/net/minecraft/world/level/entity/TransientEntitySectionManager.mapping
Labels: mappings, minor changes, 1.20.x

#250 finish mapping world/level/gameevent/
  data/net/minecraft/world/level/chunk/LevelChunk.mapping
  data/net/minecraft/world/level/gameevent/BlockPositionSource.mapping
  data/net/minecraft/world/level/gameevent/DynamicGameEventListener.mapping
  data/net/minecraft/world/level/gameevent/EntityPositionSource.mapping
  data/net/minecraft/world/level/gameevent/EuclideanGameEventListenerRegistry.mapping
  data/net/minecraft/world/level/gameevent/vibrations/VibrationInfo.mapping
  data/net/minecraft/world/level/gameevent/vibrations/VibrationSystem.mapping
Labels: mappings, 1.20.x

#253 Fix incorrect parameter ordering in one of the `DamageSource` constructors
  data/net/minecraft/world/damagesource/DamageSource.mapping
Labels: bug, mappings, minor changes, 1.20.x

#248 finish mapping world/level/chunk/
  data/net/minecraft/world/level/chunk/ChunkAccess.mapping
  data/net/minecraft/world/level/chunk/ChunkGenerator.mapping
  data/net/minecraft/world/level/chunk/ChunkGeneratorStructureState.mapping
  data/net/minecraft/world/level/chunk/ChunkStatus.mapping
  data/net/minecraft/world/level/chunk/LevelChunk.mapping
  data/net/minecraft/world/level/chunk/PalettedContainer.mapping
  data/net/minecraft/world/level/chunk/storage/ChunkSerializer.mapping
  data/net/minecraft/world/level/chunk/storage/EntityStorage.mapping
  data/net/minecraft/world/level/chunk/storage/IOWorker.mapping
  data/net/minecraft/world/level/chunk/storage/SectionStorage.mapping
Labels: mappings, 1.20.x

#247 finish mapping world/level/block/
  data/net/minecraft/world/level/block/AbstractCandleBlock.mapping
  data/net/minecraft/world/level/block/BasePressurePlateBlock.mapping
  data/net/minecraft/world/level/block/Block.mapping
  data/net/minecraft/world/level/block/Blocks.mapping
  data/net/minecraft/world/level/block/CarvedPumpkinBlock.mapping
  data/net/minecraft/world/level/block/ComparatorBlock.mapping
  data/net/minecraft/world/level/block/DecoratedPotBlock.mapping
  data/net/minecraft/world/level/block/DetectorRailBlock.mapping
  data/net/minecraft/world/level/block/DoubleBlockCombiner.mapping
  data/net/minecraft/world/level/block/EnchantmentTableBlock.mapping
  data/net/minecraft/world/level/block/FireBlock.mapping
  data/net/minecraft/world/level/block/FungusBlock.mapping
  data/net/minecraft/world/level/block/GlowLichenBlock.mapping
  data/net/minecraft/world/level/block/MossBlock.mapping
  data/net/minecraft/world/level/block/MultifaceBlock.mapping
  data/net/minecraft/world/level/block/MultifaceSpreader.mapping
  data/net/minecraft/world/level/block/NyliumBlock.mapping
  data/net/minecraft/world/level/block/PointedDripstoneBlock.mapping
  data/net/minecraft/world/level/block/SculkBehaviour.mapping
  data/net/minecraft/world/level/block/SculkBlock.mapping
  data/net/minecraft/world/level/block/SculkSensorBlock.mapping
  data/net/minecraft/world/level/block/SculkShriekerBlock.mapping
  data/net/minecraft/world/level/block/SculkSpreader.mapping
  data/net/minecraft/world/level/block/ShulkerBoxBlock.mapping
  data/net/minecraft/world/level/block/SignBlock.mapping
  data/net/minecraft/world/level/block/SpawnerBlock.mapping
  data/net/minecraft/world/level/block/SpongeBlock.mapping
  data/net/minecraft/world/level/block/StairBlock.mapping
  data/net/minecraft/world/level/block/VineBlock.mapping
  data/net/minecraft/world/level/block/WitherSkullBlock.mapping
Labels: mappings, 1.20.x

#245 finish mapping world/level/block/piston and world/level/block/state
  data/net/minecraft/world/level/block/piston/PistonHeadBlock.mapping
  data/net/minecraft/world/level/block/piston/PistonMovingBlockEntity.mapping
  data/net/minecraft/world/level/block/state/BlockBehaviour.mapping
  data/net/minecraft/world/level/block/state/properties/BlockStateProperties.mapping
  data/net/minecraft/world/level/block/state/properties/Property.mapping
Labels: mappings, 1.20.x

#246 finish mapping world/level/block/entity
  data/net/minecraft/gametest/framework/StructureUtils.mapping
  data/net/minecraft/world/level/block/entity/BannerPattern.mapping
  data/net/minecraft/world/level/block/entity/BellBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/CampfireBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/ChiseledBookShelfBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/ConduitBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/DecoratedPotBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/SculkCatalystBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/SculkSensorBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/SculkShriekerBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/SignBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/SignText.mapping
  data/net/minecraft/world/level/block/entity/StructureBlockEntity.mapping
  data/net/minecraft/world/level/block/entity/TheEndGatewayBlockEntity.mapping
Labels: mappings, 1.20.x

#244 Consistency for `RecordCodecBuilder$Instance`
  data/net/minecraft/util/Brightness.mapping
  data/net/minecraft/util/CubicSpline.mapping
  data/net/minecraft/world/entity/ai/village/poi/PoiRecord.mapping
  data/net/minecraft/world/entity/ai/village/poi/PoiSection.mapping
  data/net/minecraft/world/entity/npc/VillagerData.mapping
  data/net/minecraft/world/level/DataPackConfig.mapping
  data/net/minecraft/world/level/biome/AmbientParticleSettings.mapping
  data/net/minecraft/world/level/biome/Biome.mapping
  data/net/minecraft/world/level/biome/BiomeSpecialEffects.mapping
  data/net/minecraft/world/level/biome/CheckerboardColumnBiomeSource.mapping
  data/net/minecraft/world/level/biome/Climate.mapping
  data/net/minecraft/world/level/biome/MobSpawnSettings.mapping
  data/net/minecraft/world/level/gameevent/BlockPositionSource.mapping
  data/net/minecraft/world/level/levelgen/DensityFunctions.mapping
  data/net/minecraft/world/level/levelgen/FlatLevelSource.mapping
  data/net/minecraft/world/level/levelgen/GeodeBlockSettings.mapping
  data/net/minecraft/world/level/levelgen/GeodeCrackSettings.mapping
  data/net/minecraft/world/level/levelgen/GeodeLayerSettings.mapping
  data/net/minecraft/world/level/levelgen/feature/foliageplacers/BlobFoliagePlacer.mapping
  data/net/minecraft/world/level/levelgen/structure/Structure.mapping
Labels: mappings, 1.20.x

#251 finish mapping world/level/material,pathfinder,portal,saveddata,valid…
  data/net/minecraft/world/level/material/FlowingFluid.mapping
  data/net/minecraft/world/level/pathfinder/FlyNodeEvaluator.mapping
  data/net/minecraft/world/level/pathfinder/NodeEvaluator.mapping
  data/net/minecraft/world/level/pathfinder/Path.mapping
  data/net/minecraft/world/level/pathfinder/SwimNodeEvaluator.mapping
  data/net/minecraft/world/level/pathfinder/WalkNodeEvaluator.mapping
  data/net/minecraft/world/level/portal/PortalForcer.mapping
  data/net/minecraft/world/level/portal/PortalShape.mapping
  data/net/minecraft/world/level/saveddata/maps/MapItemSavedData.mapping
  data/net/minecraft/world/level/validation/ContentValidationException.mapping
  data/net/minecraft/world/level/validation/DirectoryValidator.mapping
  data/net/minecraft/world/level/validation/PathAllowList.mapping
Labels: mappings, 1.20.x

#256 Fix incorrect formatting preventing Enigma from correctly loading mapping files
  data/net/minecraft/gametest/framework/StructureUtils.mapping
  data/net/minecraft/world/level/block/entity/StructureBlockEntity.mapping
Labels: bug, minor changes
