Repository ParchmentMC/Parchment, pull requests merged in 2023-07, with the labels that each got.

#210 Various mappings in net/minecraft/world/level/levelgen
  data/net/minecraft/world/level/levelgen/Beardifier.mapping
  data/net/minecraft/world/level/levelgen/DensityFunction.mapping
  data/net/minecraft/world/level/levelgen/DensityFunctions.mapping
  data/net/minecraft/world/level/levelgen/NoiseRouterData.mapping
  data/net/minecraft/world/level/levelgen/OreVeinifier.mapping
  data/net/minecraft/world/level/levelgen/SurfaceSystem.mapping
  data/net/minecraft/world/level/levelgen/WorldgenRandom.mapping
  data/net/minecraft/world/level/levelgen/blending/Blender.mapping
  data/net/minecraft/world/level/levelgen/blending/BlendingData.mapping
  data/net/minecraft/world/level/levelgen/carver/CanyonWorldCarver.mapping
  data/net/minecraft/world/level/levelgen/feature/rootplacers/RootPlacer.mapping
  data/net/minecraft/world/level/levelgen/feature/trunkplacers/UpwardsBranchingTrunkPlacer.mapping
  data/net/minecraft/world/level/levelgen/placement/CountOnEveryLayerPlacement.mapping
  data/net/minecraft/world/level/levelgen/placement/PlacementContext.mapping
  data/net/minecraft/world/level/levelgen/structure/pools/JigsawPlacement.mapping
  data/net/minecraft/world/level/levelgen/synth/ImprovedNoise.mapping
  data/net/minecraft/world/level/levelgen/synth/NoiseUtils.mapping
  data/net/minecraft/world/level/levelgen/synth/NormalNoise.mapping
  data/net/minecraft/world/level/levelgen/synth/PerlinNoise.mapping
Labels: mappings, 1.20.x

#212 Update misleading `Container#canTakeItem` parameters
  data/net/minecraft/world/Container.mapping
Labels: bug, minor changes, 1.20.x

#214 Various mappings in net/minecraft/world
  data/net/minecraft/world/effect/MobEffect.mapping
  data/net/minecraft/world/inventory/ContainerSynchronizer.mapping
  data/net/minecraft/world/item/ArmorMaterials.mapping
  data/net/minecraft/world/item/BannerItem.mapping
  data/net/minecraft/world/item/BoatItem.mapping
  data/net/minecraft/world/item/CompassItem.mapping
  data/net/minecraft/world/item/FireworkRocketItem.mapping
  data/net/minecraft/world/item/Item.mapping
  data/net/minecraft/world/item/PlayerHeadItem.mapping
  data/net/minecraft/world/item/SuspiciousStewItem.mapping
  data/net/minecraft/world/item/crafting/RecipeManager.mapping
  data/net/minecraft/world/phys/Vec3.mapping
  data/net/minecraft/world/ticks/LevelChunkTicks.mapping
  data/net/minecraft/world/ticks/LevelTicks.mapping
  data/net/minecraft/world/ticks/ProtoChunkTicks.mapping
  data/net/minecraft/world/ticks/SavedTick.mapping
  data/net/minecraft/world/ticks/ScheduledTick.mapping
  data/net/minecraft/world/ticks/SerializableTickContainer.mapping
Labels: mappings, 1.20.x

#213 Various mappings in net/minecraft/world/entity
  data/net/minecraft/world/entity/AnimationState.mapping
  data/net/minecraft/world/entity/Display.mapping
  data/net/minecraft/world/entity/LivingEntity.mapping
  data/net/minecraft/world/entity/Mob.mapping
  data/net/minecraft/world/entity/ai/Brain.mapping
  data/net/minecraft/world/entity/ai/attributes/AttributeMap.mapping
  data/net/minecraft/world/entity/ai/behavior/BehaviorUtils.mapping
  data/net/minecraft/world/entity/ai/behavior/BlockPosTracker.mapping
  data/net/minecraft/world/entity/ai/behavior/MeleeAttack.mapping
  data/net/minecraft/world/entity/ai/behavior/TriggerGate.mapping
  data/net/minecraft/world/entity/ai/behavior/VillagerGoalPackages.mapping
  data/net/minecraft/world/entity/ai/goal/GoalSelector.mapping
  data/net/minecraft/world/entity/ai/navigation/GroundPathNavigation.mapping
  data/net/minecraft/world/entity/ai/navigation/PathNavigation.mapping
  data/net/minecraft/world/entity/animal/Parrot.mapping
  data/net/minecraft/world/entity/animal/allay/Allay.mapping
  data/net/minecraft/world/entity/animal/axolotl/Axolotl.mapping
  data/net/minecraft/world/entity/animal/frog/FrogAi.mapping
  data/net/minecraft/world/entity/animal/horse/AbstractChestedHorse.mapping
  data/net/minecraft/world/entity/animal/horse/AbstractHorse.mapping
  data/net/minecraft/world/entity/monster/Ghast.mapping
  data/net/minecraft/world/entity/monster/warden/AngerManagement.mapping
  data/net/minecraft/world/entity/monster/warden/WardenAi.mapping
  data/net/minecraft/world/entity/npc/InventoryCarrier.mapping
  data/net/minecraft/world/entity/npc/Villager.mapping
  data/net/minecraft/world/entity/npc/VillagerType.mapping
  data/net/minecraft/world/entity/player/ProfilePublicKey.mapping
  data/net/minecraft/world/entity/vehicle/ContainerEntity.mapping
  data/net/minecraft/world/entity/vehicle/MinecartTNT.mapping
Labels: mappings, 1.20.x

#209 Mapping/Documenting: net.minecraft.client.sound
  data/net/minecraft/client/sounds/AudioStream.mapping
  data/net/minecraft/client/sounds/ChannelAccess.mapping
  data/net/minecraft/client/sounds/LoopingAudioStream.mapping
  data/net/minecraft/client/sounds/MusicManager.mapping
  data/net/minecraft/client/sounds/SoundBufferLibrary.mapping
  data/net/minecraft/client/sounds/SoundEngine.mapping
  data/net/minecraft/client/sounds/SoundEngineExecutor.mapping
  data/net/minecraft/client/sounds/SoundEventListener.mapping
  data/net/minecraft/client/sounds/SoundManager.mapping
  data/net/minecraft/client/sounds/WeighedSoundEvents.mapping
  data/net/minecraft/client/sounds/Weighted.mapping
Labels: mappings, minor changes, 1.20.x

#221 Various mappings in net/minecraft/util
  data/net/minecraft/resources/HolderSetCodec.mapping
  data/net/minecraft/util/Crypt.mapping
  data/net/minecraft/util/CsvOutput.mapping
  data/net/minecraft/util/CubicSpline.mapping
  data/net/minecraft/util/ExtraCodecs.mapping
  data/net/minecraft/util/Graph.mapping
  data/net/minecraft/util/ModCheck.mapping
  data/net/minecraft/util/Mth.mapping
  data/net/minecraft/util/ParticleUtils.mapping
  data/net/minecraft/util/SimpleBitStorage.mapping
  data/net/minecraft/util/SortedArraySet.mapping
  data/net/minecraft/util/SpawnUtil.mapping
  data/net/minecraft/util/ToFloatFunction.mapping
  data/net/minecraft/util/datafix/fixes/BlendingDataFix.mapping
  data/net/minecraft/util/datafix/fixes/BlendingDataRemoveFromNetherEndFix.mapping
  data/net/minecraft/util/datafix/fixes/ChunkBedBlockEntityInjecterFix.mapping
  data/net/minecraft/util/datafix/fixes/ChunkStructuresTemplateRenameFix.mapping
  data/net/minecraft/util/datafix/fixes/ChunkToProtochunkFix.mapping
  data/net/minecraft/util/datafix/fixes/EntityBlockStateFix.mapping
  data/net/minecraft/util/datafix/fixes/EntityEquipmentToArmorAndHandFix.mapping
  data/net/minecraft/util/datafix/fixes/EntityRedundantChanceTagsFix.mapping
  data/net/minecraft/util/datafix/fixes/EntityRidingToPassengersFix.mapping
  data/net/minecraft/util/datafix/fixes/EntityVariantFix.mapping
  data/net/minecraft/util/datafix/fixes/FurnaceRecipeFix.mapping
  data/net/minecraft/util/datafix/fixes/ItemRenameFix.mapping
  data/net/minecraft/util/datafix/fixes/LeavesFix.mapping
  data/net/minecraft/util/datafix/fixes/LevelDataGeneratorOptionsFix.mapping
  data/net/minecraft/util/datafix/fixes/MemoryExpiryDataFix.mapping
  data/net/minecraft/util/datafix/fixes/MissingDimensionFix.mapping
  data/net/minecraft/util/datafix/fixes/OptionsAddTextBackgroundFix.mapping
  data/net/minecraft/util/datafix/fixes/OverreachingTickFix.mapping
  data/net/minecraft/util/datafix/fixes/RedstoneWireConnectionsFix.mapping
  data/net/minecraft/util/datafix/fixes/StructureSettingsFlattenFix.mapping
  data/net/minecraft/util/datafix/fixes/TrappedChestBlockEntityFix.mapping
  data/net/minecraft/util/datafix/fixes/VillagerDataFix.mapping
  data/net/minecraft/util/eventlog/EventLogDirectory.mapping
  data/net/minecraft/util/monitoring/jmx/MinecraftServerStatistics.mapping
  data/net/minecraft/util/thread/ProcessorMailbox.mapping
Labels: mappings, 1.20.x

#220 Various mappings in net/minecraft/util/datafix and net/minecraft/util/profiling
  data/net/minecraft/client/profiling/ClientMetricsSamplersProvider.mapping
  data/net/minecraft/util/datafix/fixes/BitStorageAlignFix.mapping
  data/net/minecraft/util/datafix/fixes/ChunkHeightAndBiomeFix.mapping
  data/net/minecraft/util/datafix/fixes/ChunkPalettedStorageFix.mapping
  data/net/minecraft/util/datafix/fixes/ChunkProtoTickListFix.mapping
  data/net/minecraft/util/datafix/fixes/LeavesFix.mapping
  data/net/minecraft/util/datafix/fixes/SavedDataFeaturePoolElementFix.mapping
  data/net/minecraft/util/datafix/fixes/WorldGenSettingsFix.mapping
  data/net/minecraft/util/profiling/FilledProfileResults.mapping
  data/net/minecraft/util/profiling/ProfileResults.mapping
  data/net/minecraft/util/profiling/SingleTickProfiler.mapping
  data/net/minecraft/util/profiling/jfr/Percentiles.mapping
  data/net/minecraft/util/profiling/jfr/SummaryReporter.mapping
  data/net/minecraft/util/profiling/jfr/parse/JfrStatsParser.mapping
  data/net/minecraft/util/profiling/jfr/serialize/JfrResultJsonSerializer.mapping
  data/net/minecraft/util/profiling/jfr/stats/GcHeapStat.mapping
  data/net/minecraft/util/profiling/jfr/stats/NetworkPacketSummary.mapping
  data/net/minecraft/util/profiling/metrics/MetricSampler.mapping
  data/net/minecraft/util/profiling/metrics/profiling/ActiveMetricsRecorder.mapping
  data/net/minecraft/util/profiling/metrics/profiling/ProfilerSamplerAdapter.mapping
  data/net/minecraft/util/profiling/metrics/profiling/ServerMetricsSamplersProvider.mapping
  data/net/minecraft/util/profiling/metrics/storage/MetricsPersister.mapping
Labels: mappings, 1.20.x

#215 Various mappings for net/minecraft/client/gui
  data/net/minecraft/client/gui/components/AbstractSelectionList.mapping
  data/net/minecraft/client/gui/components/AbstractWidget.mapping
  data/net/minecraft/client/gui/components/BossHealthOverlay.mapping
  data/net/minecraft/client/gui/components/ChatComponent.mapping
  data/net/minecraft/client/gui/components/DebugScreenOverlay.mapping
  data/net/minecraft/client/gui/components/MultiLineLabel.mapping
  data/net/minecraft/client/gui/components/MultilineTextField.mapping
  data/net/minecraft/client/gui/components/toasts/SystemToast.mapping
  data/net/minecraft/client/gui/font/TextFieldHelper.mapping
  data/net/minecraft/client/gui/font/providers/UnihexProvider.mapping
  data/net/minecraft/client/gui/narration/NarrationThunk.mapping
  data/net/minecraft/client/gui/narration/ScreenNarrationCollector.mapping
  data/net/minecraft/client/gui/screens/ChatScreen.mapping
  data/net/minecraft/client/gui/screens/LevelLoadingScreen.mapping
  data/net/minecraft/client/gui/screens/LoadingDotsText.mapping
  data/net/minecraft/client/gui/screens/LoadingOverlay.mapping
  data/net/minecraft/client/gui/screens/SoundOptionsScreen.mapping
  data/net/minecraft/client/gui/screens/achievement/StatsScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/BookEditScreen.mapping
  data/net/minecraft/client/gui/screens/inventory/InventoryScreen.mapping
  data/net/minecraft/client/gui/screens/recipebook/RecipeBookComponent.mapping
  data/net/minecraft/client/gui/screens/recipebook/RecipeBookPage.mapping
  data/net/minecraft/client/gui/screens/recipebook/RecipeCollection.mapping
  data/net/minecraft/client/gui/screens/reporting/ChatSelectionLogFiller.mapping
  data/net/minecraft/client/gui/screens/social/PlayerEntry.mapping
  data/net/minecraft/client/gui/screens/social/SocialInteractionsPlayerList.mapping
  data/net/minecraft/client/gui/screens/worldselection/EditGameRulesScreen.mapping
  data/net/minecraft/client/gui/screens/worldselection/PresetEditor.mapping
  data/net/minecraft/client/gui/screens/worldselection/WorldOpenFlows.mapping
  data/net/minecraft/client/gui/screens/worldselection/WorldSelectionList.mapping
Labels: mappings, 1.20.x

#226 Various mappings in the rest of net/minecraft
  data/net/minecraft/Util.mapping
  data/net/minecraft/advancements/critereon/EntitySubPredicate.mapping
  data/net/minecraft/advancements/critereon/EntityVariantPredicate.mapping
  data/net/minecraft/advancements/critereon/LighthingBoltPredicate.mapping
  data/net/minecraft/advancements/critereon/PlayerTrigger.mapping
  data/net/minecraft/commands/Commands.mapping
  data/net/minecraft/commands/SharedSuggestionProvider.mapping
  data/net/minecraft/commands/arguments/ParticleArgument.mapping
  data/net/minecraft/commands/arguments/ResourceOrTagArgument.mapping
  data/net/minecraft/commands/arguments/ResourceOrTagKeyArgument.mapping
  data/net/minecraft/commands/arguments/blocks/BlockStateArgument.mapping
  data/net/minecraft/commands/arguments/selector/EntitySelector.mapping
  data/net/minecraft/commands/arguments/selector/options/EntitySelectorOptions.mapping
  data/net/minecraft/commands/synchronization/ArgumentUtils.mapping
  data/net/minecraft/core/BlockPos.mapping
  data/net/minecraft/core/HolderGetter.mapping
  data/net/minecraft/core/RegistryAccess.mapping
  data/net/minecraft/core/RegistryCodecs.mapping
  data/net/minecraft/core/Vec3i.mapping
  data/net/minecraft/gametest/framework/GameTestHelper.mapping
  data/net/minecraft/gametest/framework/MultipleTestTracker.mapping
  data/net/minecraft/gametest/framework/StructureUtils.mapping
  data/net/minecraft/gametest/framework/TestCommand.mapping
  data/net/minecraft/nbt/NbtOps.mapping
  data/net/minecraft/nbt/TagType.mapping
  data/net/minecraft/realms/RealmsObjectSelectionList.mapping
  data/net/minecraft/tags/TagManager.mapping
  data/net/minecraft/tags/TagNetworkSerialization.mapping
Labels: mappings, 1.20.x

#223 Various mappings in net/minecraft/network
  data/net/minecraft/network/ConnectionProtocol.mapping
  data/net/minecraft/network/chat/ComponentUtils.mapping
  data/net/minecraft/network/chat/FilterMask.mapping
  data/net/minecraft/network/chat/LastSeenMessagesTracker.mapping
  data/net/minecraft/network/chat/LastSeenMessagesValidator.mapping
  data/net/minecraft/network/chat/Style.mapping
  data/net/minecraft/network/protocol/BundlerInfo.mapping
  data/net/minecraft/network/protocol/game/ClientboundCommandsPacket.mapping
  data/net/minecraft/network/protocol/game/ClientboundLevelChunkPacketData.mapping
  data/net/minecraft/network/protocol/game/ClientboundLightUpdatePacketData.mapping
  data/net/minecraft/network/protocol/game/DebugPackets.mapping
  data/net/minecraft/network/protocol/game/VecDeltaCodec.mapping
  data/net/minecraft/network/syncher/EntityDataSerializers.mapping
Labels: mappings, 1.20.x

#224 Various mappings in net/minecraft/data
  data/net/minecraft/data/BlockFamily.mapping
  data/net/minecraft/data/HashCache.mapping
  data/net/minecraft/data/Main.mapping
  data/net/minecraft/data/loot/EntityLootSubProvider.mapping
  data/net/minecraft/data/loot/LootTableSubProvider.mapping
  data/net/minecraft/data/models/BlockModelGenerators.mapping
  data/net/minecraft/data/models/model/ModelTemplate.mapping
  data/net/minecraft/data/structures/NbtToSnbt.mapping
  data/net/minecraft/data/tags/IntrinsicHolderTagsProvider.mapping
  data/net/minecraft/data/worldgen/AncientCityStructurePieces.mapping
  data/net/minecraft/data/worldgen/AncientCityStructurePools.mapping
  data/net/minecraft/data/worldgen/BastionHoglinStablePools.mapping
  data/net/minecraft/data/worldgen/BastionHousingUnitsPools.mapping
  data/net/minecraft/data/worldgen/BastionPieces.mapping
  data/net/minecraft/data/worldgen/BastionSharedPools.mapping
  data/net/minecraft/data/worldgen/BastionTreasureRoomPools.mapping
  data/net/minecraft/data/worldgen/DesertVillagePools.mapping
  data/net/minecraft/data/worldgen/DimensionTypes.mapping
  data/net/minecraft/data/worldgen/NoiseData.mapping
  data/net/minecraft/data/worldgen/PillagerOutpostPools.mapping
  data/net/minecraft/data/worldgen/PlainVillagePools.mapping
  data/net/minecraft/data/worldgen/SavannaVillagePools.mapping
  data/net/minecraft/data/worldgen/SnowyVillagePools.mapping
  data/net/minecraft/data/worldgen/SurfaceRuleData.mapping
  data/net/minecraft/data/worldgen/TaigaVillagePools.mapping
  data/net/minecraft/data/worldgen/TerrainProvider.mapping
  data/net/minecraft/data/worldgen/VillagePools.mapping
  data/net/minecraft/data/worldgen/biome/BiomeData.mapping
  data/net/minecraft/data/worldgen/biome/OverworldBiomes.mapping
  data/net/minecraft/data/worldgen/features/AquaticFeatures.mapping
  data/net/minecraft/data/worldgen/features/CaveFeatures.mapping
  data/net/minecraft/data/worldgen/features/EndFeatures.mapping
  data/net/minecraft/data/worldgen/features/MiscOverworldFeatures.mapping
  data/net/minecraft/data/worldgen/features/NetherFeatures.mapping
  data/net/minecraft/data/worldgen/features/OreFeatures.mapping
  data/net/minecraft/data/worldgen/features/PileFeatures.mapping
  data/net/minecraft/data/worldgen/features/TreeFeatures.mapping
  data/net/minecraft/data/worldgen/placement/AquaticPlacements.mapping
  data/net/minecraft/data/worldgen/placement/CavePlacements.mapping
  data/net/minecraft/data/worldgen/placement/EndPlacements.mapping
  data/net/minecraft/data/worldgen/placement/MiscOverworldPlacements.mapping
  data/net/minecraft/data/worldgen/placement/NetherPlacements.mapping
  data/net/minecraft/data/worldgen/placement/OrePlacements.mapping
  data/net/minecraft/data/worldgen/placement/PlacementUtils.mapping
  data/net/minecraft/data/worldgen/placement/TreePlacements.mapping
  data/net/minecraft/data/worldgen/placement/VegetationPlacements.mapping
  data/net/minecraft/data/worldgen/placement/VillagePlacements.mapping
Labels: mappings, 1.20.x

#222 Various mappings in net/minecraft/server
  data/net/minecraft/server/LoggedPrintStream.mapping
  data/net/minecraft/server/Main.mapping
  data/net/minecraft/server/PlayerAdvancements.mapping
  data/net/minecraft/server/ReloadableServerResources.mapping
  data/net/minecraft/server/ServerAdvancementManager.mapping
  data/net/minecraft/server/ServerFunctionLibrary.mapping
  data/net/minecraft/server/ServerFunctionManager.mapping
  data/net/minecraft/server/WorldLoader.mapping
  data/net/minecraft/server/commands/DataPackCommand.mapping
  data/net/minecraft/server/commands/ExecuteCommand.mapping
  data/net/minecraft/server/commands/ItemCommands.mapping
  data/net/minecraft/server/commands/LootCommand.mapping
  data/net/minecraft/server/commands/RaidCommand.mapping
  data/net/minecraft/server/commands/SeedCommand.mapping
  data/net/minecraft/server/commands/TeleportCommand.mapping
  data/net/minecraft/server/commands/TitleCommand.mapping
  data/net/minecraft/server/commands/data/DataCommands.mapping
  data/net/minecraft/server/dedicated/DedicatedServerProperties.mapping
  data/net/minecraft/server/dedicated/Settings.mapping
  data/net/minecraft/server/level/ChunkMap.mapping
  data/net/minecraft/server/level/ColumnPos.mapping
  data/net/minecraft/server/level/DistanceManager.mapping
  data/net/minecraft/server/level/PlayerRespawnLogic.mapping
  data/net/minecraft/server/level/ServerBossEvent.mapping
  data/net/minecraft/server/level/ServerChunkCache.mapping
  data/net/minecraft/server/level/ServerLevel.mapping
  data/net/minecraft/server/level/ServerPlayer.mapping
  data/net/minecraft/server/level/ServerPlayerGameMode.mapping
  data/net/minecraft/server/level/ThreadedLevelLightEngine.mapping
  data/net/minecraft/server/level/TickingTracker.mapping
  data/net/minecraft/server/level/WorldGenRegion.mapping
  data/net/minecraft/server/network/LegacyQueryHandler.mapping
  data/net/minecraft/server/network/ServerConnectionListener.mapping
  data/net/minecraft/server/network/ServerGamePacketListenerImpl.mapping
  data/net/minecraft/server/network/TextFilterClient.mapping
  data/net/minecraft/server/packs/VanillaPackResources.mapping
  data/net/minecraft/server/packs/repository/BuiltInPackSource.mapping
  data/net/minecraft/server/packs/repository/FolderRepositorySource.mapping
  data/net/minecraft/server/packs/repository/ServerPacksSource.mapping
  data/net/minecraft/server/packs/resources/FallbackResourceManager.mapping
  data/net/minecraft/server/packs/resources/MultiPackResourceManager.mapping
  data/net/minecraft/server/packs/resources/ResourceProvider.mapping
  data/net/minecraft/server/players/GameProfileCache.mapping
  data/net/minecraft/server/rcon/thread/RconClient.mapping
Labels: mappings, 1.20.x

#227 Update Util.mapping
  data/net/minecraft/Util.mapping
Labels: mappings, minor changes, 1.20.x

#229 Various mappings in com/mojang
  data/com/mojang/blaze3d/font/SpaceProvider.mapping
  data/com/mojang/blaze3d/vertex/BufferBuilder.mapping
  data/com/mojang/math/MatrixUtil.mapping
  data/com/mojang/realmsclient/RealmsMainScreen.mapping
  data/com/mojang/realmsclient/client/FileDownload.mapping
  data/com/mojang/realmsclient/client/FileUpload.mapping
  data/com/mojang/realmsclient/client/RealmsClient.mapping
  data/com/mojang/realmsclient/dto/RealmsServer.mapping
  data/com/mojang/realmsclient/gui/RealmsWorldSlotButton.mapping
  data/com/mojang/realmsclient/gui/RowButton.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsBackupScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsBrokenWorldScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsConfigureWorldScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsPendingInvitesScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsPlayerScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsResetWorldScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsSelectWorldTemplateScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsSlotOptionsScreen.mapping
  data/com/mojang/realmsclient/gui/screens/RealmsUploadScreen.mapping
  data/com/mojang/realmsclient/gui/task/DataFetcher.mapping
  data/com/mojang/realmsclient/util/RealmsUtil.mapping
  data/com/mojang/realmsclient/util/task/GetServerDetailsTask.mapping
Labels: mappings, 1.20.x

#232 Mappings for `WoodlandMasionPieces`
  data/net/minecraft/world/level/levelgen/structure/structures/WoodlandMansionPieces.mapping
Labels: mappings, minor changes, 1.20.x
