Repository ParchmentMC/Parchment, pull requests merged in 2024-11, with the labels that each got.

#309 Add GitHub Actions to replace TeamCity as CI
  .github/workflows/bleeding.yml
  .github/workflows/nightly.yml
  .github/workflows/prs.yml
  .github/workflows/release.yml
  README.md
  build.gradle
Labels: enhancement, 1.21.x

#302 Fix typos
  data/net/minecraft/util/datafix/fixes/SavedDataFeaturePoolElementFix.mapping
  data/net/minecraft/world/level/levelgen/flat/FlatLevelGeneratorSettings.mapping
Labels: bug, mappings, minor changes, 1.21.x

#308 Rename RandomSource.triangle arguments
  data/net/minecraft/util/RandomSource.mapping
Labels: bug, mappings, minor changes, 1.21.x

#304 Javadocs for Entity, LivingEntity, and Player
  data/net/minecraft/world/entity/Entity.mapping
  data/net/minecraft/world/entity/LivingEntity.mapping
  data/net/minecraft/world/entity/player/Player.mapping
Labels: mappings, 1.21.x

#297 Update to 1.21.1
  build.gradle
  data/net/minecraft/client/renderer/ShaderInstance.mapping
  data/net/minecraft/commands/arguments/EntityArgument.mapping
  data/net/minecraft/commands/arguments/GameProfileArgument.mapping
  data/net/minecraft/commands/arguments/ScoreHolderArgument.mapping
  data/net/minecraft/commands/arguments/selector/EntitySelectorParser.mapping
Labels: mappings, 1.21.x

#310 Fix validation errors
  data/net/minecraft/commands/arguments/EntityArgument.mapping
  data/net/minecraft/commands/arguments/GameProfileArgument.mapping
  data/net/minecraft/commands/arguments/ScoreHolderArgument.mapping
  data/net/minecraft/commands/arguments/selector/EntitySelectorParser.mapping
Labels: bug, mappings, minor changes, 1.21.x
